### ISSUE TITLE
[BUG] Mixin library is not compatible with finenv.RetainLuaState

### ISSUE THREAD

**Issue by rpatters1** [finale-lua/lua-scripts#137]
**Describe the bug**
The `mixin.lua` library is not compatible with the `finenv.RetainLuaState` property introduced in RGP Lua 0.60.

**To Reproduce**
1. Run the following script.
```lua
local mixin = require("library.mixin")
dialog = finale.FCCustomLuaWindow()
finenv.RetainLuaState = true
```
2. Run it a second time.

**Expected behavior**
The second time the script fails on
```lua
dialog = finale.FCCustomLuaWindow()
```
with
```
...mixin.lua:200: bad argument #1 to 'pairs' (table expected, got nil)"
```

**Desktop (please complete the following information):**
 - OS: macOS 10.12.1 (Monterey)
 - Finale 27.1
 - RGP Lua Version 0.61

**Additional context**
I tried changing mixin.lua:446 to
```lua
finale_ = finale_ or finale
```
but it makes no difference. I also tried this script:
```lua
if not finenv.RetainLuaState then
   mixin = require("library.mixin")
end
dialog = finale.FCCustomLuaWindow()
finenv.RetainLuaState = true
```
but it also makes no difference.

I'm still investigating it, but I though I would raise the issue so we know about it.

@ThistleSifter

**Comment by rpatters1** [comment]
More information:

I was able to fix the issues with `finenv.RetainLuaState` by changing the `get_parent_class` function to use `finale_` instead of `_G.finale`. But now the following script fails, and it fails identically in RGP Lua and JW Lua. This is with no edits to `mixin.lua`

```lua
local mixin = require("library.mixin")
local dialog1 = finale.FCCustomLuaWindow()
print("ClassName of dialog1 is "..dialog1:ClassName())
local dialog2 = finale.FCCustomLuaWindow()
print("ClassName of dialog2 is "..dialog2:ClassName())
```
It fails because `dialog2` comes back `nil`.

A comment from @ThistleSifter would be most helpful, because this is no longer an issue with RGP Lua.

**Comment by ThistleSifter** [comment]
Ah, thanks for the heads up. Looking into this now.
