### ISSUE TITLE
problem in configuration library?

### ISSUE THREAD

**Issue by jwink75** [finale-lua/lua-scripts#149]
configuration.lua, line 119 reads:
 `for param_name, def_val in pairs(parameter_list) do`

But this depends on parameter_list being already populated with data and keys defined, where what is really needed here is to fill out parameter_list with data from the file. I think this line should actually be:

`for param_name, def_val in pairs(file_parameters) do`

In adapting the configuration script for use in JetStream, it was broken until I made that change. It's entirely possible that I wasn't using it right to begin with, but after making the change it works like a champ.

**Comment by Nick-Mazuk** [comment]
@rpatters1 will be able to give a better answer, but I'm guessing this was intentional and not a bug. Take for instance the usage of the `get_parameters` function:

https://github.com/finale-lua/lua-scripts/blob/07e4125fdb6fa6bfcad3a5970be321b942abdda4/src/chord_accidental_adjust_down.lua#L13-L16

You'll notice that we're passing in a `config` with a single key of `vertical_increment`. However, the config file may have dozens of other keys present, perhaps even thousands (not realistic, but a possibility). So instead of looping through every single value in the config file, it makes sense to only loop through the ones we need.

I'm curious how things were broken when using it for JetStream, since to me I think using either `parameter_list` or `file_parameters` would produce the same results (not counting the performance differences).

**Comment by jwink75** [comment]
The way I was setting it up was to declare a table:
`local config = {}`
Then use the library function to read parameters from the config file into that table. So the problem I was having here is that the library function iterates through _that_ table, which is empty. So when I would try to read any values from the table later, they were all nil.

Once I switched it to file_parameters, it was working because it loaded up all the parameters in the config file.

So... Do I gather right that I was actually supposed to ask it for a single value essentially? Or maybe a few? Like "Hey, config file, what value should I use for horizontal_nudge?"

You said "instead of looping through every single value in the config file"... but doesn't the function end up doing that anyway as it reads through the lines of the file?

**Comment by jwink75** [comment]
By the way, here's my "save" code:
`function config_save(config_settings)
  local path = path_set("com.jetstreamfinale.config.txt")
  local file_w = io.open(path.LuaString, "w") 
  for key, val in pairs(config_settings) do
    file_w:write(key.." = "..val.."\n")
  end
  file_w:close()
end -- config_save()`

I'll try to adapt that to the configuration library's approach soon...

**Comment by Nick-Mazuk** [comment]
> The way I was setting it up was to declare a table: `local config = {}` Then use the library function to read parameters from the config file into that table. So the problem I was having here is that the library function iterates through _that_ table, which is empty. So when I would try to read any values from the table later, they were all nil.
> 
> Once I switched it to file_parameters, it was working because it loaded up all the parameters in the config file.

Ah, yes. In this case you would need to use the `file_parameters`.

The difference between your scenario and the library function is the library function's goal is to get the config values for the provided keys. It sounds like the JetStream code isn't providing any keys, but rather just wants to read all keys from the config file.



> So... Do I gather right that I was actually supposed to ask it for a single value essentially? Or maybe a few? Like "Hey, config file, what value should I use for horizontal_nudge?"

They way you're doing it is perfectly acceptable in my opinion. At the scales we're dealing with (i.e., 10s or 100s of config values, tops), you're not going to see any real improvements whether you use parameter_list or file_parameters. And you'd need some discrepancies in between the desired keys and the keys in the config to get see any improvements.

Sorry if I'm confusing you at all! I was focusing on a different issue the other day where this difference really did matter.

> You said "instead of looping through every single value in the config file"... but doesn't the function end up doing that anyway as it reads through the lines of the file?

So yes, you're going to loop over all the file_parameters at least once when you read the file.

With the way Robert implemented it, you only need to loop over it once. If you loop over the file_parameters, you'll loop over every value in the file twice.

**Comment by rpatters1** [comment]
The code is working as designed. The requirement for configuration files was:

1. Caller functions whether there is a config file or not.
2. No dependencies between configuration file and caller. That is, the caller doesn't depend on what's in the config file, and the configurator does not care if the caller changes its list of configurable parameters.

The caller provides a table containing all of its configurable parameters. The configurator iterates that table and overrides any values it finds in the config file. Upon return, the caller does not know or care if any were overridden.
