### ISSUE TITLE
Allow for users to download "suites" of scripts

### ISSUE THREAD

**Issue by Nick-Mazuk** [finale-lua/lua-scripts#169]
Currently on the website, downloading scripts is simple—one download per script, and one script per download. 

However, many of the scripts could be bundled together to form a "suite" of scripts. For instance, there are many scripts for moving dynamics/chords/staves/expressions/measure-numbers up/down. These all fall into the "move things vertically" category. Wouldn't it be nice for users to be able to download all of these with one click?

Or perhaps another example with a stronger case. Most of my unpublished scripts now are just slight variations on one idea. I have 14 scripts to change key signatures. I have another 12 or so for time signatures. I have 8 to change barlines. Etc.

I've resisted publishing these since that could flood our download page with a lot of noise. Want to search for a script related to key signatures? Too bad, you have 14 more scripts to wade through that are almost identical.

Now I have these scripts broken out since Keyboard Maestro makes it very quick and easy to select each of them. And if I were to combine these into a single script with a menu to select the specific key (for instance), now it's no better than Finale's key signature menu—and you lose out on the massive speed gains from the KM/Lua combo.

So if there was some way I could also publish these scripts but be able to group them into a suite of scripts with a single download button, that would allow others to get use out of my scripts while still making it easy to find scripts on the website.

No idea how to do this yet, but creating an issue in case anyone else has ideas or wants to help.

**Comment by rpatters1** [comment]
To me it seems like (taking your key signature scripts as examples) it should only be one script with parameters. RGP Lua has the ability to load the same script multiple times with different parameters defined in the prefix for each (as well as different menu, description, and undo text). So leveraging that seems like a possible solution. (This is pretty much why I added that feature.)

One way you could do it now is to package your script(s) along with all the configurations in a separate xml file and bundled with a separate copy of RGP Lua for a stand-alone menu item. But I don't like this approach because it encourages splattering copies of RGP Lua throughout the plugin directory.

Another possibility is to enhance RGP Lua to look for a config file in the same location as the script and add additional configurations there. Then each script could be bundled with all the different possible configurations for each option. Maybe it could be a lighter-weight format than xml. A simple delimited string per menu option could do it. Then all the user would need to do is download one script and one text file with menu options.

**Comment by rpatters1** [comment]
On further reflection, it might be be better to build into the `plugindef` function the ability to create multiple menu options with different parameters. Similar to the old Parameters feature of jwlua, but without any need for external setup.

What do you think?

**Comment by rpatters1** [comment]
Here is a proposed way of using the `plugindef` function. This example would combine all the `pitch_entry_double_*.lua` scripts into a single script. This uses an approach similar to jwlua's parameters feature. (I looked at reusing that, but I don't want to have to be compatible with how jwlua treats it.)

```lua
function plugindef()
    finaleplugin.RequireSelection = true
    finaleplugin.Author = "Nick Mazuk"
    finaleplugin.Copyright = "CC0 https://creativecommons.org/publicdomain/zero/1.0/"
    finaleplugin.Version = "1.0.2"
    finaleplugin.Date = "March 31, 2021"
    finaleplugin.CategoryTags = "Pitch"
    finaleplugin.AuthorURL = "https://nickmazuk.com"
    finaleplugin.AdditionalMenuOptions = [[
        Double third up
        Double octave down
        Double octave up
    ]]
    finaleplugin.AdditionalUndoText = [[
        Double third up
        Double octave down
        Double octave up
    ]]
    finaleplugin.AdditionalDescriptions = [[
        Double third up
        Double octave down
        Double octave up
    ]]
    finaleplugin.AdditionalPrefixes = [[
        diatonic_interval = 2
        diatonic_interval = -7
        diatonic_interval = 7
    ]]
    return "Double third down", "Double third down", "Doubles the current note a diatonic third lower"
end

diatonic_interval = diatonic_interval or -2

local transposition = require("library.transposition")
local note_entry = require("library.note_entry")

function pitch_entry_double()
    for entry in eachentrysaved(finenv.Region()) do
        local note_count = entry.Count
        local note_index = 0
        for note in each(entry) do
            note_index = note_index + 1
            if note_index > note_count then
                break
            end
            local new_note = note_entry.duplicate_note(note)
            if nil ~= new_note then
                transposition.diatonic_transpose(new_note, diatonic_interval)
            end
        end
    end
end

pitch_entry_double()
```

RGP Lua add a menu option for the main return value (in this case "Double third down"). It would then also add an additional menu option for each of the strings in `finaleplugin.AdditionalMenuOptions`.

**Comment by rpatters1** [comment]
I have pushed a working example of what I'm thinking of to the branch `RGP-changes-for-rgplua-0.62`. It works with the version of RGP Lua running on my dev box but is fully backwards compatible with previous versions. (By means of deprecating scripts that are no longer needed and marking them not to run with 0.62.)

Let me know what you think.

**Comment by Nick-Mazuk** [comment]
Ooh, I like that functionality. It also makes maintaining them easier since it's just one script, not 14!

For the `finaleplugin.AdditionalPrefixes` field, how would it work if there are multiple variables you'd like to change?

For reference, all my scripts I referenced in the original post are pre-RGP Lua.

**Comment by rpatters1** [comment]
The lua language treats line breaks the same as spaces, so you could write a prefix like:

```lua
param1 = 1 param2 = 3.5 param3 = "EVPU"
```

Or you could have the prefix parameter be an index into a configuration table.

**Comment by Nick-Mazuk** [comment]
Ok, that makes sense. So each line can be any arbitrary piece of Lua to setup the script.

**Comment by rpatters1** [comment]
Yes, that's the approach I was thinking of.

**Comment by Nick-Mazuk** [comment]
That works, and will dramatically simplify some of my scripts. I like it!

If a script needs many separate parameters, we may need to rethink this. Though one could argue that if you need to configure 10 different variables that they should really be separate scripts at that point.

**Comment by rpatters1** [comment]
I would create a configuration table at that point, if it really needed to be one script. Then the prefix could be a index into the table.

Or the prefix could be a string that names a require library that actually executed the script. The flexibility of this approach seems pretty high to me.

**Comment by Nick-Mazuk** [comment]
True, that's a really elegant way to do this.

Since it sounds like this is coming in v0.62, I'm going to go ahead and close this issue.

**Comment by rpatters1** [comment]
I'm reopening the issue to get feedback on one further issue. There are a number of plugin suites already in existence that can be collapsed into a single script using the new 0.62 feature. The question is what to do about the old scripts. Do we

- delete them and expect users to use 0.62?
- leave them alone but perhaps mark them not to load in 0.62+?
- move them to a subfolder, e.g., `/deprecated`?
- other ideas?

In the `RGP-changes-for-rgplua-0.62` branch, I went with the second option, but honestly I think I prefer the third or the first to the second. The less code to maintain the better.

**Comment by Nick-Mazuk** [comment]
Good point.

I'd prefer the first option myself. Especially since RGP Lua is technically in beta, I think it's acceptable to make breaking changes for the scripts. Though for this, we should definitely mark the minimum plugin version in the plugindef and I should finish #122.

**Comment by rpatters1** [comment]
Ok. Another thing to consider is showing all the `AdditionalDescriptions` as well as the main description.

**Comment by Nick-Mazuk** [comment]
> Ok. Another thing to consider is showing all the `AdditionalDescriptions` as well as the main description.

On the website? Possibly.

Are the returned values from the `plugindef` overwritten by `finaleplugin.AdditionalMenuOptions`, `finaleplugin.AdditionalUndoText`, and `finaleplugin.AdditionalDescriptions`? In other words, would we be able to rewrite the above example's plugindef as:

```lua
function plugindef()
    finaleplugin.RequireSelection = true
    finaleplugin.Author = "Nick Mazuk"
    finaleplugin.Copyright = "CC0 https://creativecommons.org/publicdomain/zero/1.0/"
    finaleplugin.Version = "1.0.2"
    finaleplugin.Date = "March 31, 2021"
    finaleplugin.CategoryTags = "Pitch"
    finaleplugin.AuthorURL = "https://nickmazuk.com"
    finaleplugin.AdditionalMenuOptions = [[
        Double third up
        Double octave down
        Double octave up
    ]]
    finaleplugin.AdditionalUndoText = [[
        Double third up
        Double octave down
        Double octave up
    ]]
    finaleplugin.AdditionalDescriptions = [[
        Double third up
        Double octave down
        Double octave up
    ]]
    finaleplugin.AdditionalPrefixes = [[
        diatonic_interval = 2
        diatonic_interval = -7
        diatonic_interval = 7
    ]]
    return "Double notes at interval", "Double notes at interval", "Doubles notes at specific intervals"
end
```

Then use `Double notes at interval` for the title on the website? Yet each script will have its own independent title?

If so, we may not need to show each additional description on the website. If that seems necessary for a specific script, the author can put that in the `finaleplugin.Notes` field.
