### ISSUE TITLE
Tie Library

### ISSUE THREAD

**Issue by rpatters1** [finale-lua/lua-scripts#171]
This "issue" is to discuss the support for `FCTieMod` that is coming in RGP Lua 0.62. I have full support now working for `FCTieMod` on my development machine. However, I want to alert this community to a big issue around editing ties in Finale. To initialize an `FCTieMod` so that you can modify a tie's placement, you have to know:

- the direction (up or down) of the tie
- both the tied-from and tied-to notes
- whether it has Outer or Inner placement
- whether it starts/ends on note side or stem side
- whether it crosses a system break
- the specific combination of preferences selected in `FCTiePrefs`
- the specific combination of preferences for ties selected in `FCLayerPrefs`

Just looking down the list, you begin to realize the number of dependencies to know these (especially the tie direction) is quite high. Furthermore, it depends entirely on reverse-engineering Finale's current behavior, which is sometimes quite idiosyncratic in corner cases such as ties to nothing. Finally, even if you figure all this out, the code is extremely brittle if Finale's behavior changes.

I know of no way to get Finale to tell us this information. There are no "tie metrics" in the PDK, more's the pity.

The good news is that I figured out all this code over twenty years ago for my Tie Mover plugin. And Finale's behavior for ties does not appear meaningfully to have changed since then. The question then comes down to where to put this code. Originally my idea was to lard it into the PDK Framework. This would have the advantage of making it available to any Lua programmer. But it turns out that whether you can find both notes in the tie depends a great deal on how the `FCNote` instance was created. And if I'm not going to handle that for Lua scripts, the whole plan starts to unravel. You get into issues around how to keep references to variables alive, and it turns into a rabbit hole.

So the solution I elected instead was to force the Lua programmer to do all the work. I provide all the methods on `FCTieMod` to initialize the Tie Placement endpoints, but the Lua script has to figure out what to pass in. Obviously, this has the drawback that basically no one will likely ever take the trouble.

Enter `tie.lua`, a tie library that I would like to add to this repo. It basically is a dump of all the work I did in ~2000 to figure out Finale's behavior. Now initializing `FCTieMod` for editing tie placement is as simple as:

```lua
-- This code nudges selected ties up by 12 evpu.
-- It doesn't handle the case where a note has both a tie end and a tie start.
-- That's a refinement for a real implementation.

local tie = require("library.tie")

tie_prefs = finale.FCTiePrefs()
tie_prefs:Load(0)

for entry in eachentrysaved(finenv.Region()) do
    for note in each(entry) do
        local tie_mod
        if note.Tie then
            tie_mod = finale.FCTieMod(finale.TIEMODTYPE_TIESTART)
        elseif note.TieBackwards then
            tie_mod = finale.FCTieMod(finale.TIEMODTYPE_TIEEND)
        end
        if tie_mod then
            local loaded = tie_mod:LoadAt(note)
            tie.activate_endpoints(note, tie_mod, finenv.UI():IsPageView(), tie_prefs) -- activate any endpoint that needs it
            tie_mod.StartVerticalPos = tie_mod.StartVerticalPos + 12
            tie_mod.EndVerticalPos = tie_mod.EndVerticalPos + 12
            tie_mod:SaveAt(note)
         end
      end
   end
end
```

All the magic happens in `tie.activate_endpoints`.

The more I think about this approach, the more I think it is the correct one. Now the Lua script owns all the variables. But more importantly, if Finale ever changes its behavior around ties, we don't have to wait for a new version of RGP Lua to incorporate those changes. Same goes if I have introduced bugs in extracting my Tie Mover code or if my original code had errors. They will be easy to fix if the code is in Lua.

I know that @Nick-Mazuk doesn't like incorporating library code that isn't used anywhere. But this seems like a chicken and egg situation. No one is likely to use ties without the library.

**Comment by jwink75** [comment]
Much appreciated Robert! Nick can just deal with it :)

**Comment by Nick-Mazuk** [comment]
Go ahead and add the library functions.
