### ISSUE TITLE
[BUG]Lua Linter reveals bug in staff_explode_layers.lua

### ISSUE THREAD

**Issue by rpatters1** [finale-lua/lua-scripts#177]
**Describe the bug**
The Lua Linter reveals a bug in the `get_note_count` function in `staff_explode_layers.lua`. The variable `max_note_count` is never defined, which leads the function always returning zero, or perhaps, always returning the last note_count in the region. (I'm not sure which, but either way it's wrong.)

Also, shouldn't `get_note_count` be in a library? (Maybe `note_entry.lua`?)

@cv-on-hub

**Comment by cv-on-hub** [comment]
Thanks Robert. I've added the correction to Pull Request #174
