### ISSUE TITLE
Could "library.configuration" use config files in the source directory?

### ISSUE THREAD

**Issue by cv-on-hub** [finale-lua/lua-scripts#179]
The configuration library is great, but to work needs the User to read the instructions AND create a directory in the right place, with the right name and right access permissions.

I understand the neatness of sequestering config files in a "script_settings" folder, but Lua is unable to create or manipulate directories (os.execute[mkdir] doesn't work on macOS) so it can't automate the process for users. On the other hand Lua scripts can easily maintain config files in their own SetRunningLuaFolderPath() directory. Couldn't the config library look there before checking inside "script_settings"? ".config" and ".txt" files should be entirely benign in that location, and titled correctly will sit quietly next to their source files.

**Comment by rpatters1** [comment]
One reason it is in a sub directory is to keep it out of the repo. I have a separate private repo for my `script_settings` sub directory that tracks chances to my config files. If they lived in the same directory as the scripts they would have to be excluded with `.gitignore` and there would be no way to track changes to them.

I have no objection if it also searches the script folder.

**Comment by rpatters1** [comment]
This code works for me on macOS. It creates a `script_settings` subdirectory where it should be:

```lua
local path = 'mkdir "'..finenv:RunningLuaFolderPath()..'script_settings"'
print(path)

os.execute(path)
```

**Comment by cv-on-hub** [comment]
Now it all makes sense - thank you! And of course you're right - that mkdir works on macOS, so all is good. (I had copied "path:SetRunningLuaFolderPath()" from your configuration.get_parameters_from_file routine which apparently fails on mkdir).

**Comment by Nick-Mazuk** [comment]
One tangent is that since most configs are in the format `*.config.txt`, we can always add that line to the .gitignore.

For organization reasons, I'd prefer to keep adding the configs to the `script_settings` subdirectory. But it can't hurt to add that extra line to the .gitignore.

**Comment by cv-on-hub** [comment]
Now that I know script_settings dir can be created there's no problem using that route. (and I kinda like the .config suffix!)
