### ISSUE TITLE
Addition of `eachstaff` built-in iterator function

### ISSUE THREAD

**Issue by rpatters1** [finale-lua/lua-scripts#203]
It seems that there is a broad misconception in the Finale-Lua community that it is possible to iterate through the staves in an `FCMusicRegion` by using the `StartStaff` and `EndStaff` properites. This is unfortunately not the case. Finale increments staff numbers in the order you add them, not the order in which they appear. Instead, scripts should iterate on `StartSlot` and `EndSlot` and then use `CalcStaffNumber` inside the loop to get the staff number.

I would like to encapsulate this logic in a new built-in iterator function `eachstaff`. You would use it as follows:

```lua
for staff in eachstaff(finenv.Region()) do
    -- do something with the staff, such as:
    print("Staff: ", staff)
end
```

However, it might be nice to have a solution for versions before RGP Lua 0.63 (and JW Lua). We could include it in one of the library requires, but ideally it should be added to the global namespace rather than to a library namespace. That way the calling code could be agnostic as to whether it is built into RGP Lua or added by the library.

What do you guys think? Should we provide back-version support? Should we add it to the global namespace, if so, and what's the best way to do it?

FWIW: here is the `eachstaff` iterator function I propose to add to the built-in functions.

```lua
function eachstaff(region)
    local measure = region.StartMeasure
    local slotno = region:GetStartSlot() - 1
    return function ()
        while true do
            slotno = slotno + 1
            if slotno <= region:GetEndSlot() then
                local staff_num = region:CalcStaffNumber(slotno)
                if staff_num > 0 then
                    return staff_num
                end
            end
            return nil
        end
    end
end
```

Tagging all the recent contributors: @ThistleSifter @jwink75 @cv-on-hub @MichaelMcClennan

**Comment by Nick-Mazuk** [comment]
I think it's a good idea, though I think either it should be built into RGP Lua in the global namespace (like `eachentrysaved`), or it should be written purely in Lua and included in the function library (perhaps `iterators.eachstaff`?).

I think adding the function purely for use in this repository and moving it into the global namespace could be problematic.

**Comment by rpatters1** [comment]
FWIW: I am for keeping JW Lua support when it is easy. I'm just not sure how easy this counts as.

**Comment by rpatters1** [comment]
RGP Lua doesn't understand any of the Lua error messages, so knowing when to suggest upgrading could be a challenge.

I guess my question boils down to, do we even need a `iterators.eachstaff`?

**Comment by Nick-Mazuk** [comment]
> I guess my question boils down to, do we even need a `iterators.eachstaff`?

Only if we really want backwards compatibility (and only for scripts in this repo). My opinion is that it's not worth it, but I can be convinced otherwise.
