### ISSUE TITLE
Revisions for recruitment site instructions

### ISSUE THREAD

**Issue by cv-on-hub** [finale-lua/lua-scripts#210]
I decided to re-clone the repository and discovered a couple of incosistencies in the instructions. I started at the "Adding Scripts" page: https://www.finalelua.com/docs/getting-started/adding-scripts. It gives the wrong access point for fin-lua ... `/finale-lua/jw-lua` instead of `/finale-lua/lua-scripts`. It also promised "a bright green button that says Fork" but for me that button was missing with the "Fork" facility hidden behind the "Code" button.

**Comment by Nick-Mazuk** [comment]
Thanks for pointing that out!

If you want to submit a PR to fix it, here's the file to change:

https://github.com/finale-lua/lua-scripts/blob/master/docs/getting-started/adding-scripts.md

If not, I *may* have time today or tomorrow.

**Comment by cv-on-hub** [comment]
Didn't notice that I'd left this open!

**Comment by Nick-Mazuk** [comment]
In a GitHub PR, you can actually automatically close an issue by adding the following line to the description:

```
fix [link to issue]
```

So in this case:

```
fix https://github.com/finale-lua/lua-scripts/issues/210
```

Then when the PR is merged, GitHub will automatically close the issue for you.
