### ISSUE TITLE
[BUG] Doc page for tie.calc_tie_span

### ISSUE THREAD

**Issue by rpatters1** [finale-lua/lua-scripts#220]
**Describe the bug**
The library documentation generator may be confused if a function has multiple return values.

**To Reproduce**
The function [`tie.calc_tie_span`](https://www.finalelua.com/docs/library/tie#calc_tie_span) has garbled documentation pages compared to the comment in the code.

**Expected behavior**
1. I would have expected a bullet list instead of a code block.
2. The parameters should be listed instead of garbled.
3. There should be multiple return values.

Here is the current comment block:
```lua
--[[
% calc_tie_span

Calculates the (potential) start and end notes for a tie, given an input note. The
input note can be from anywhere, including from the `eachentry()` iterator functions.
The function returns 3 values:

    - A FCNoteLayerEntry containing both the start and and notes (if they exist).
    You must maintain the lifetime of this variable as long as you are referencing either
    of the other two values.
    - The potential or actual start note of the tie (taken from the FCNoteLayerEntry above).
    - The potential or actual end note of the tie (taken from the FCNoteLayerEntry above).

Be very careful about modifying the return values from this function. If you do it within
an iterator loop from `eachentry()` or `eachentrysaved()` you could end up overwriting your changes
with stale data from the iterator loop. You may discover that this function is more useful
for gathering information than for modifying the values it returns.

@ note (FCNote) the note for which to calculated the tie span
@ [for_tied_to] if true, searches for a note tying to the input note. Otherwise, searches for a note tying from the input note.
@ [tie_must_exist] if true, only returns notes for ties that already exist.
: (FCNoteLayerEntry) A new FCNoteEntryLayer instance that contains both the following two return values.
: (FCNote) The start note of the tie.
: (FCNote) The end note of the tie.
]]
```

Let me know if there is a change I can make to the comment to avoid this behavior.

**Comment by Nick-Mazuk** [comment]
> 1. I would have expected a bullet list instead of a code block.

This behavior is actually apart of the [Markdown spec](https://github.github.com/gfm/#indented-code-blocks). If a line is indented by 4 spaces, it will be parsed as a code block, no matter if it would otherwise be a list, heading, or something else.



> 2\. The parameters should be listed instead of garbled.

The syntax for the second two parameters are not quite correct. They still need a type before the description:

```
@ [for_tied_to] (boolean) if true, searches for a note tying to the input note. Otherwise, searches for a note tying from the input note.
@ [tie_must_exist] (boolean) if true, only returns notes for ties that already exist.
```



> 3\. There should be multiple return values.

While currently it is possible to use multiple return values (on a single line), I agree that your proposed solution is more intuitive. I'm working on a adding this feature now.
