### ISSUE TITLE
meter_change.lua

### ISSUE THREAD

**Issue by rpatters1** [finale-lua/lua-scripts#221]
I am working on enhancing `meter_change.lua` so that it can optionally only change the meter in one bar based on invoking with a shift key. In the process I discovered that it leaves cruft around if it is overwriting composite meters. To fix this I changed `SetBeat` to `RemoveCompositeTop` and `SetBeatDuration` to `RemoveCompositeBottom`. The `Set...` methods should really never be used (unless you are building up your own key signature).

Also, `time_sig:Save()` does nothing (and returns false) if you are saving for a measure (as opposed to an independent timesig in a cell). It may not ever do anything. (I don't remember at the moment.)

I am in progress of fixing these. What prompted me to create this issue is a question:

Do we really want it to change to the end of the document? It seems like Finale's behavior of changing to the next meter change would be more useful.

**Comment by Nick-Mazuk** [comment]
I agree that changing to the next meter change (or the end of the doc if none exists) is probably the better option.

**Comment by rpatters1** [comment]
Okay, here's another wrinkle. Does it make sense to stop at the end of a movement? There are various ways to detect a movement change, but what occurs to me (at a minimum) is to stop if the time signature is set to "Always Show" for that measure. That seems to me to be better than what Finale does, but ymmv.
