### ISSUE TITLE
[BUG] - Serious garbling in the /dist directory

### ISSUE THREAD

**Issue by cv-on-hub** [finale-lua/lua-scripts#244]
As of just now (GMT 04:00) most if not all of the files in the /dist directory are seriously garbled. This includes all scripts downloadable from finalelua.com/scripts
@Nick-Mazuk @rpatters1

**Comment by Nick-Mazuk** [comment]
This would likely be a result of https://github.com/finale-lua/lua-scripts/pull/240

It is intentional that the bundled scripts have different contents from before.

Are you noticing any bugs in particular?

**Comment by Nick-Mazuk** [comment]
Follow up, I see what happened.

It seems like the library I started using to bundle the files thinks that all library files resolve to `src/library/general_library.lua`. And likely when I tested things earlier Finale was using outdated scripts somehow.

Figuring out a fix to this now.

**Comment by Nick-Mazuk** [comment]
Closing since this is fixed in #245.
