### ISSUE TITLE
Fingering & colouring

### ISSUE THREAD

**Issue by Ozfrog** [finale-lua/lua-scripts#278]
Hello - working on refingering some Bach Preludes and Fugues as the commercial products aren't very helpful. Younger students have small hands and / or haven't learned to sight read sufficiently well enough  to instantly interpret the needed fingering.
Single notes are ok but the number never goes exactly where it would best be suited - often between staves instead of over / under. Could a script be written to;
select finger number
place as desired - above stave, between stave or under stave.
Now chords.
These are a real pain - 
1. Finale puts ALL fingerings on top of each other - lots of moving them around manually to get something readable.
2. I'd like to able to enclose chord fingerings in brackets for clarity.
3. Again - choice of placement in regards to staves would be a bonus.
____________________________________________________________

Colouring.
Finale will let me assign a colour to a "layer" but I'm more interested in separate notes.
Especially in the above Fugues where Mr. Bach loves to keep notes held across bar lines for lengths depending on note values.
I have used "Inkscape" to successfully achieve this, but it's another long process.

I'll try to paste a .pdf of a finished Fugue - about 3 week's work :)
[Fugue IV Book 1 Coloured_Page 2.pdf](https://github.com/finale-lua/lua-scripts/files/9221490/Fugue.IV.Book.1.Coloured_Page.2.pdf)

**Comment by rpatters1** [comment]
I'm fairly certain that colors in Finale work with screen display only. (An exception is the "Color Noteheads" setting in Score Manager, but it applies only to scale degrees.)

If Finale can't do it, a script can't make it do it. More's the pity.

**Comment by rpatters1** [comment]
Never mind. I see the "Display Colors" option in the Print Dialog, which I assume will replicate the screen colors. But sfaik Finale does not have note-by-note coloration, nor expression-by-expression coloration.

**Comment by Ozfrog** [comment]
Hello,

I'm fairly certain that colors in Finale work with screen display only. (An exception is the "Color Noteheads" setting in Score Manager, but it applies only to scale degrees.)
If Finale can't do it, a script can't make it do it. More's the pity.

> Oh dear I did hold out some small hope.
Back to Inkscape I guess, at least for the colour stuff. Did you look at my .pdf?
Thanks for your time to reply.
L. Dixon
_______

**Comment by Ozfrog** [comment]
> 
> Never mind. I see the "Display Colors" option in the Print Dialog, which I assume will replicate the screen colors. But sfaik Finale does not have note-by-note coloration, nor expression-by-expression coloration.
> 
> Yes - my findings too - and I haven’t even tried printing to see the effects.

> Cheers
> 

L. Dixon
_______

**Comment by Nick-Mazuk** [comment]
Closing since it seems like this isn't possible in Finale. Feel free to reopen.
