### ISSUE TITLE
RFC: Supports feature or exit

### ISSUE THREAD

**Issue by Nick-Mazuk** [finale-lua/lua-scripts#279]
Yesterday we merged the `client` library (https://www.finalelua.com/docs/library/client).

One thing I realized is that this means we're abstracting away the versions of JW/RGP Lua and Finale that are needed for a script. Overall, I think this is a net good thing as it should improve reliability and stability amongst programs. Developers don't need to remember what versions of JW/RGP Lua and Finale that are required, they just need to ensure the client can do the required things.

However, I could see this making us less likely to define our required software versions in the `plugindef` (which to be fair, most of us aren't doing anyways). This means it's less likely that users can know why things aren't working as expected.

Now in some places we are using the capabilities as a form of progressive enhancement:

```lua
if client.supports_this_feature() then
    do_something()
else
    do_something_else()
end
```

However, other parts of the codebase just check if something is supported:

```lua
if client.supports_this_feature() then
    do_something()
end
-- what happens here if that feature is not supported?
-- nothing will happen and the user won't get any errors
```

For these cases, I suggest we add a new type of functions to the client library: `client.supports_x_or_exit()`. These functions will determine if `x` feature is supported. If it's not, it will exit the program and give the user instructions on how to use the script (e.g., upgrade your version of Lua, use a newer version of Finale, etc.).

Additionally, every "supports" function in the `client` library will have an `or_exit` equivalent.

```lua
function client.supports_modeless_dialog()
    return finenv.IsRGPLua
end

function client.supports_modeless_dialog_or_exit()
    if client.supports_modeless_dialog() then
        return true
    end
    -- show dialog "This script uses modeless dialogs which are not available on JW Lua. Please use RGP Lua instead to use this script."
end
```

From this, we can give great, standardized error messages to users while improving developer experience.

@rpatters1 @cv-on-hub @ThistleSifter

**Comment by rpatters1** [comment]
Is it possible for a library function to exit the script? Otherwise every script will have to exit exit exit. (It could be layers deep.)

**Comment by Nick-Mazuk** [comment]
You can exit by throwing an error:

```
error("message")
```

**Comment by rpatters1** [comment]
In that case I recommend that the library func throw the error rather than displaying a dialog. I'm pretty sure RGP Lua will then show that error in a dialog.

**Comment by rpatters1** [comment]
Anyway, it's worth a test.

**Comment by Nick-Mazuk** [comment]
Throwing the error did bring up a dialog:

```lua
error("This script uses modeless dialogs which are not available on JW Lua. Please use RGP Lua instead to use this script.")
```

<img width="372" alt="Screen Shot 2022-07-29 at 10 52 07 AM" src="https://user-images.githubusercontent.com/5659171/181816779-f58892c8-e7a0-4f46-8e78-fda3a9b9e36d.png">

**Comment by ThistleSifter** [comment]
I think this is a good idea. I have a couple of suggestions:

**Naming**
I would use `assert` in the function name instead of `or_exit`. It's more Lua-y and more descriptive of what the function actually does (rather than naming it after a side effect which isn't necessarily guaranteed).

**Structure**
Rather than filling up the `client` library file with lots of `if not client.supports_x then error("error message") end` and `function client.supports_xyz, function client.assert_supports_xyz`, I'd suggest restructuring the library along these lines:

```lua

-- Add all tests here
local tests = {
    modeless_dialogs = function()
        return finenv.IsRGPLua
    end,
}

-- Add any custom error messages here. If not specified, a generic error will be thrown.
local error_messages = {
   modeless_dialogs = "insert message here",
}

local client = {}

function client.supports(feature)
    return tests[feature] and tests[feature]() or false
end

function client.assert_supports(feature)
    if not client.supports(feature) then
        if error_messages[feature] then
            error(error_messages[feature], 2)
        end
        -- Generic error message
        error("Your Finale version does not support " .. string.gsub(feature, "_", " "), 2)
    end
end
```

Then usage would look like this:
```lua
local xyz = require("library.xyz")
...
local client = require("library.client")

client.assert_supports("feature_a")
client.assert_supports("feature_b")

function plugin_body()
    if client.supports("feature_x") then
        ...
    end
end

plugin_body()
```

**Error Level**
I'd add an optional error level parameter to `assert_supports`, to give greater control across a wider variety of potential uses. (eg `client.assert_supports("feature_x", 2)`)

**Comment by rpatters1** [comment]
I really like the approach suggested by @ThistleSifter. About the error level, I wonder if passing error level 0 isn't the best option. That suppresses the file/line information in the message and presents a much cleaner message to the user. (Who is the target of these particular messages.)

**Comment by Nick-Mazuk** [comment]
I do think @ThistleSifter's approach is definitely better. I'd just make one slight modification to keep the error messages closer to the features.

```lua
local features = {
    modeless_dialogs = {
        test = function()
            return finenv.IsRGPLua
        end,
        error = "insert message here"
    }
}

local client = {}

function client.supports(feature)
    return features[feature].test()
end

function client.assert_supports(feature)
    if not client.supports(feature) then
        if features[feature].error then
            error(features[feature].error, 0)
        end
        -- Generic error message
        error("Your Finale version does not support " .. string.gsub(feature, "_", " "), 2)
    end
end
```

Note the two changes:

1. There aren't two tables, but rather a single `features` table. That allows us to colocate feature name, test, and error message.
2. I'm no longer testing to see if a feature is defined in the table. This could cause errors, but as a developer I want those errors. If I mistype a feature, I want to find that out quickly before I submit the PR. The best way to do that is to have a thrown error when I test out the script locally. Otherwise, especially if you don't assert, I'd be looking for a logic issue, not something that in other languages would be a compile-time issue.

> About the error level, I wonder if passing error level 0 isn't the best option. That suppresses the file/line information in the message and presents a much cleaner message to the user. (Who is the target of these particular messages.)

I agree. Passing error code 0 is a much better user experience.

To be honest, I can't think of a reason why you'd want a non-0 exit code in this case, so I'm not sure if it should even be an optional parameter. Curious on all your thoughts on this.

**Comment by rpatters1** [comment]
I am interested if @ThistleSifter has ideas about why we might want to have error levels other than 0. But absent those, I tend to agree that hard-coding 0 makes sense.

**Comment by Nick-Mazuk** [comment]
Since I have some time and it seems like we're in agreement on the bigger picture, I'm going to go ahead and create a PR to implement this. That way we can quickly weed out places where the existing API is used.

All the other little things (like the features/tests/errors tables organization) is mostly internal to this library and that'll be much easier to refactor later should we need it.

**Comment by Nick-Mazuk** [comment]
Closing since #289 implements this feature.
