### ISSUE TITLE
RFC: link to videos in plugindef

### ISSUE THREAD

**Issue by Nick-Mazuk** [finale-lua/lua-scripts#296]
Several of us have videos online about the scripts we've made. Wouldn't it be awesome to show off those videos on the website?

That would also let users have a much better idea of what each script does before they download it.

To do this, I propose we add a new field in the plugindef:

```lua
finaleplugin.YouTubeVideo = "https://youtu.be/HR9dwIov59A"
```

All that's required is a valid YouTube URL as the value. I've already written code to be able to parse the YouTube video IDs from all valid YouTube video URLs, then display the iFrame. So even the longer formats (e.g., https://www.youtube.com/watch?v=HR9dwIov59A or https://www.youtube.com/watch?v=KYy-12if_Oc&list=PLsFZ0c2Wsoy_g72PAtjv3zLYT8i9dHDmr) will work.

I propose we restrict this to YouTube videos as that'll make it dramatically easier for me to add this to the website. And if someone wants to use another service like Vimeo, they can still link to it from the `Notes` field as you can already do today.

cc @cv-on-hub @ThistleSifter @rpatters1 @jwink75

**Comment by rpatters1** [comment]
Excellent idea. Maybe keep the name generic ("OnlineVideo" perhaps), since YouTube, like everything else on the web, might not last forever.

**Comment by Nick-Mazuk** [comment]
I can get behind `finaleplugin.OnlineVideo`, or perhaps even just `finaleplugin.Video`?

**Comment by rpatters1** [comment]
I almost said `Video` and it think it's all that needs to be said.

**Comment by rpatters1** [comment]
Or `VideoUrl`. Your call.

**Comment by Nick-Mazuk** [comment]
Ok, I think I'll go with `VideoUrl` just in case in the future we find a way to share videos with this not via a url (no idea how we'd do that, but at least we won't be boxed in if we do).

**Comment by rpatters1** [comment]
I'm going to close this issue, since it seems like we got a decision. Reopen if needed.
