### ISSUE TITLE
[BUG] is mixin still throwing bugs?

### ISSUE THREAD

**Issue by cv-on-hub** [finale-lua/lua-scripts#316]
I realise that @Nick-Mazuk closed this issue, but the `/dist` version of `hairpin_creator.lua` is still throwing errors from the `mixin` portion when it calls a dialog (invoked with option key). The 'raw' script works fine. Does this just need re-merging or is there still an issue with `mixins`? (a runtime error is reported at "Line 3961" - something to do with control creation override).
https://github.com/finale-lua/lua-scripts/blob/master/dist/hairpin_creator.lua

**Comment by Nick-Mazuk** [comment]
It's possible this has a different cause from #264.

Remerging wouldn't fix this as the `dist` versions of all scripts are generated every single time a new commit gets added to master.

**Comment by ThistleSifter** [comment]
That's odd. I have a show tonight so I won't be able to look into this today, but I'll set aside some time tomorrow night to investigate.

**Comment by ThistleSifter** [comment]
Quick theory, just jotting this down: 
```lua
function require(item)
    if __imports[item] then
        return __imports[item]()
    else
        error("module '" .. item .. "' not found")
    end
end
```
This `require` function executes the functions every time the library is `require`'d, but Lua's native `require` function only executes the file once and then stores the result. Then every subsequent time a library is included, Lua just retrieves the stored result, which also means that all `private` variables maintain their scope, etc etc. With this function, a new scope is created on every `require`.

**Comment by ThistleSifter** [comment]
@Nick-Mazuk

Replacing the opening lines with this fixes the problem:
```lua
local __imports = {}
local __import_results = {}

function require(item)
    if not __imports[item] then
        error("module '" .. item .. "' not found")
    end

    if __import_results[item] == nil then
        __import_results[item] = __imports[item]()
        if __import_results[item] == nil then
            __import_results[item] = {}
        end
    end

    return __import_results[item]
end
```
