### ISSUE TITLE
[BUG] A new error in downloaded script using 'mixin' library

### ISSUE THREAD

**Issue by cv-on-hub** [finale-lua/lua-scripts#360]
Downloaded `dist` version of `rest_offsets.lua` throws an error every SECOND time it is invoked (presumably because of RetainLuaState re-setting on the first failure).

As follows:
ERROR: rest_offsets.lua:7863:
Object is not mixin-enabled
lines 7862-7864:
```
local function catch_and_rethrow(tryfunczzz, levels, ...)
     return mixin_private.pcall_wrapper(levels, pcall(function(...) return 1, tryfunczzz(...) end, ...))
end
```

**Comment by cv-on-hub** [comment]
... the same error behaviour with `layers_swap_selective.lua`

**Comment by rpatters1** [comment]
Oops. This will be a tough nut to crack. Because each run of the script is a new Lua chunk, any previously defined locals are out of scope and will eventually be garbage-collected.

**Comment by ThistleSifter** [comment]
It's not too bad. I've got a working solution which should work consistently in any scenario (bundled or not). The only downside is that I needed to add 2 globals so the mixin data is technically no longer private. That and it adds a few lines of code at the top of each `mixin` file. I just need to finish applying it to all of the `mixins` and the `mixin_helper` library.

Progress is here: https://github.com/ThistleSifter/jw-lua-scripts/tree/mixin-retainluastate-fix

**Comment by cv-on-hub** [comment]
Inasmuch as I understand little of what the two of you are talking about this sounds like good news!

**Comment by jwink75** [comment]
LOL glad I’m not the only one, Carl :)

**Comment by ThistleSifter** [comment]
@rpatters1 Going further down the rabbit hole, I've been doing some testing and it seems that if a function is stored as a global, its upvalues are preserved with `RetainLuaState`. Have I got this correct? This is the test script I was using:

```lua
local bar
if finenv.RetainLuaState then
    bar = function()
        finenv.UI():AlertInfo("Subsequent", "test")
    end
else
    bar = function()
        finenv.UI():AlertInfo("Original", "test")
    end
end

foo = foo or function()
    bar()
end

foo()

finenv.RetainLuaState = true
```
In my tests, it always displays `Original`.

**Comment by ThistleSifter** [comment]
[rest_offsets_global.txt](https://github.com/finale-lua/lua-scripts/files/9531488/rest_offsets_global.txt)

@cv-on-hub Can you test the attached file and let me know if it gives you any errors?
