### ISSUE TITLE
Hairpin Creator Settings

### ISSUE THREAD

**Issue by composerdude** [finale-lua/lua-scripts#368]
**What do you need help with?**
The Hairpin Creator lua is really great, but I'd love to tweak it a bit more to match some of the settings I had when I was using the JW Pattern (Hairpins) plugin. If anyone has a tweaked lua or some coding I could add to the existing lua, it would be greatly appreciated!

Main feature missing:
I would like this feature: Hairpins will not go to rests or on staves that have no entries 
(for example, if you have a 3 beat swell and select the whole bar, the lua should only crescendo for the 1st 3 beats. additionally, if you select 5 staves and only 2 have notes in them, it should only put hairpins on the staves with notes.

Additional features:
There is a bug that it does not perform well on the last bar of a file. any fixes?
Any way to adjust the padding in the middle for a 1 bar swell (with no dynamics)?

**What have you tried?**
I have been through all of the hairpin creator configuration settings and looked through the code to the best of my ability.
Thank you in advance for any help!

**Comment by cv-on-hub** [comment]
Sorry @composerdude - as the writer of `hairpin_creator` I don't normally trawl through the "Issues" section here unless I'm specifically tagged in a post.

I can't realistically offer fixes for all of that, but will consider:
1. Thanks for bringing up the bug in "the last bar" but can now see it, and need to add a test for `nil` end region.
2. Omitting "empty" staves in the middle of a stack is a good idea and will consider including it.
3. Padding in the middle of a swell bar without dynamics respond to the global `left` and `right` horizontal offset numbers, though of course this will simultaneously affect both ends of both hairpins.

I consider _"hairpins will not go to rests"_ as atypical usage that can be overcome with more judicious selection of source region. (If you've selected a region like that a script shouldn't arbitrarily decide to override your choice). This isn't a one-script-fits-every-conceivable-purpose facility like Elbsound's `Perfect Layout`. It simplifies basic hairpin creation, but selecting _appropriate_ sources and following up with some simple manual adjustments should generally be assumed!

**Comment by composerdude** [comment]
@cv-on-hub Thank you very much! The lua is really great and very much appreciated for my workflow! Thank you for all of the info!
