### ISSUE TITLE
Voiced Parts issues (Finale 27.3)

### ISSUE THREAD

**Issue by rpatters1** [finale-lua/lua-scripts#382]
Finale 27.3 has added Special Tools edits to Voiced Parts, which means that the Voiced Parts feature is now a usable feature instead of a curiosity. However, Voiced Parts present a challenge to plugins (including Lua scripts) in that Finale implements Voiced Parts in the drawing phase. That means with certain options, the entry data the plugin sees does not match what is drawn in the part.

It turns out that one can find out if a specific note is visible by searching the note metrics for it, but the most pathological edge cases can lead to entire sequences of notes being represented in the part as a single rest. I don't think that rest can be isolated in an FCNoteEntry instance.

Much as I would like to implement a global fix that requires no changes to scripts, I don't think that is possible. But I could at least

- add an FCNote::CalcVisibleInCurrentPart method
- change FCNoteEntry::CalcHighest/Lowest methods to take note visibility into account

But if I do change the calc highest/lowest methods, then they could potentially return null if there aren't any visible notes. So that's a potential breaking change.

I would welcome suggestions as to how much of this to build into RGP Lua and how much to leave to Lua programmers.

**Comment by ThistleSifter** [comment]
> That means with certain options, the entry data the plugin sees does not match what is drawn in the part.

Does it affect other note entry data or just note visibility?

&nbsp;
> It turns out that one can find out if a specific note is visible by searching the note metrics for it, but the most pathological edge cases can lead to entire sequences of notes being represented in the part as a single rest. I don't think that rest can be isolated in an FCNoteEntry instance.

So does that mean that there is no way for plugins to interact with or manipulate that rest?

**Comment by rpatters1** [comment]
Plugins see all the note data, but only some of it appears in the part.

I can't see anyway for plugins to interact with or manipulate the fake rests. Mind you, this is a very pathological edge case and probably is not worth a lot of effort to address.

**Comment by ThistleSifter** [comment]
I've been pondering this for the past couple of days. Unfortunately I don't have the time to dig into it myself at the moment, but I did have a couple of thoughts.

If the note entry is not visible in the part, should it even be accessible by a Lua script when in that part? Does that mean that as 
things are, notes can be accessed/edited that aren't actually in the current part?

I think my first instinct (I like to start a bit out there) would be to try out having a kind of dummy/readonly FCNoteEntry taking the place of the hidden note entries. That way the data that the Lua script sees is at least trying to match what is in the part. (Also, is it possible that the fake rests may become accessible in a future version of Finale?)

If you are going to add a FCNote::CalcVisibleInCurrentPart method, would that be better off being on FCNoteEntry instead (or both)? If the modified CalcHighest/Lowest methods are called and return null, that's what they're basically saying anyway so it would be helpful to have that formalised and would make it easier for script writers.

If you are going to modify the CalcHighest/Lowest methods, I see three options:
- **Modify them** - breaking change
- **Add an optional argument (eg _CalcHighestNote ([FCNote]\* pCeiling = NULL, skipInvisible = false)_)** - technically not a breaking change, but somewhat ugly
- **Add CalcHighestVisible\*/CalcLowestVisible\* methods** - Not breaking and cleaner for Lua scripts to use, but possibly unnecessary duplication and API clutter?

**Comment by rpatters1** [comment]
It isn't possible to make the hidden FCNoteEntries be "dummies", at least, not without a lot of effort and risk. Finale is sending them all in.

After having worked with this for a while, I think the best approach is your option 1. While technically a breaking change, the only situation where it breaks is an extremely unlikely one, if voiced parts are being used in a sensible musical way. Meanwhile, it obviates the need for any additional client code other than null checking. (And if null checking isn't there, the consequences are not huge for a Lua script. It issues a runtime error in an extreme edge case: hardly an unusual occurrence in our world.)

**Comment by rpatters1** [comment]
Also, you can try this for yourself now. Voice Parts is not a new feature, and you can see for yourself what happens internally if some of the notes are hidden in a voiced part.

**Comment by rpatters1** [comment]
This has been addressed with modified versions of the CalcHighest/Lowest methods in version 0.65
