### ISSUE TITLE
Floating EVPU in dialog:CreateMeasurementEdit

### ISSUE THREAD

**Issue by cv-on-hub** [finale-lua/lua-scripts#389]
I guess this is mostly addressed to @ThistleSifter.

I'm working on a script using your CreateMeasurementUnitPopup in a FCXCustomLuaWindow, and the EVPU values in MeasurementEdits always revert to integers. How can I force EVPUs to be floats? (Line widths are either EFIX or decimal precision).

**Comment by ThistleSifter** [comment]
`FCXMeasurementEdit` has three methods that change the underlying format used when converting between measurement units:
- `SetTypeMeasurementInteger()` - Whole EVPUs (this is the default)
- `SetTypeMeasurement()` - EVPUs with decimal
- `SetTypeMeasurementEfix()` - EFIXs with decimal

It sounds like the one you're after is `SetTypeMeasurement()`

**Comment by cv-on-hub** [comment]
Ah - many thanks @ThistleSifter - that does the trick! Is it usual to get significant rounding errors when swapping Units? 1.75 EVPU, for instance, drops to 1.72 when swapping to points and back. (Script attached if you're interested). 
[gracenote_slash.txt](https://github.com/finale-lua/lua-scripts/files/10326310/gracenote_slash.txt)

**Comment by ThistleSifter** [comment]
Hmm, I'll have to look into that further. In theory it shouldn't, at least not with the example figure you gave.

**Comment by cv-on-hub** [comment]
Without any user changes, these values in EVPU:
```
measurement_unit = 1
upstem_artic_y_offset = -32
downstem_artic_y_offset = 8
upstem_artic_x_offset = 4
downstem_line_width = 2.25
```
get stored in the User prefs file as this in cm:
```
measurement_unit = 3
upstem_artic_y_offset = -32.003746032715
downstem_artic_y_offset = 8.0003700256348
upstem_artic_x_offset = 3.9996180534363
downstem_line_width = 2.2498559951782
```
Converting back to EVPU shows the rounding errors in the prefs file:
```
upstem_artic_y_offset = -32
downstem_artic_y_offset = 8
upstem_artic_x_offset = 3.9900000095367
downstem_line_width = 2.2400000095367
```

**Comment by ThistleSifter** [comment]
I was looking into this just now and I noticed that Finale's inbuilt dialogs have the same issue.

For example, open _Document -> Document Options... ->Piano Braces and Brackets_ and play around with changing measurement units.

**Comment by cv-on-hub** [comment]
> Finale's inbuilt dialogs have the same issue.

You're right. I'd previously checked out "Smart Shape Options" which seems to be generally more accurate in the translation back and forth, but that could just be more flexible starting values.Is there any way that there could be (for instance) a rounding to 3 or 4 decimal places on each translation?

**Comment by ThistleSifter** [comment]
The solution I have circumvents changing the underlying value when changing measurement units. I still need to test it, but if you want to give it a go, you can find it here: https://github.com/ThistleSifter/jw-lua-scripts/blob/fcx-ctrl-measurement-edit/src/mixin/FCXCtrlMeasurementEdit.lua

There is always going to be a certain amount of deviation in the stored number from the displayed number anyway due to floating point inaccuracy.

**Comment by cv-on-hub** [comment]
@ThistleSifter - I can't tell what you've changed in `FCXCtrlMeasurementEdit.lua` but it works incredibly well. Better than the built-in Finale conversions.
