### ISSUE TITLE
[BUG] Explode scripts should use note_entry.delete_note instead of DeleteNote()

### ISSUE THREAD

**Issue by rpatters1** [finale-lua/lua-scripts#395]
**Describe the bug**
Staff explode scripts should be using the library function `note_entry.delete_note()` rather than the PDK Framework function `FCNoteEntry::DeleteNote`. This is because the DeleteNote function does not clean up entry details associated with the note, such as custom noteheads, accidental mods, tie mods, etc.

**Comment by cv-on-hub** [comment]
Since all the affected scripts have been amended, should this ISSUE now be closed?

**Comment by rpatters1** [comment]
Normally this is done by referencing the issue # in the description of the pull request that fixes it, e.g.:

Fixes #xyz. (Where "xyz" is the number of the issue.)

That automatically closes the issue when the PR is merged. Honestly I thought I saw that you had done that in the PR for this issue, or I would have said something. But I'm closing it now.
