### ISSUE TITLE
[BUG] Cue notes create

### ISSUE THREAD

**Issue by asherber** [finale-lua/lua-scripts#416]
**Describe the bug**
Invoking the "Cue Notes Create" plugin leads to an error, "No writable member "UseCheckboxes"

**To Reproduce**
1. Open a Finale file
2. Select a range of source measures
3. Invoke the plugin
4. Modal dialog for selecting cue name, `*** new name ***` is selected
5. Click OK, enter cue name, click OK
6. Error displays

**Screenshots**
![image](https://user-images.githubusercontent.com/5248041/215332785-c4cbc9f3-708e-48d6-a597-34346bbd5738.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Finale Version 25.5
 - JW Lua Version 0.65
 - Script Name: Cue Notes Create

**Additional context**
@cv-on-hub

**Comment by rpatters1** [comment]
Are you using the latest version from the repo? There have been a couple of recent commits that might have addressed this.

Also, it would be helpful to know if the version in `src` has the same issue.

**Comment by asherber** [comment]
Yes, using latest from repo. (And this line of code has been present since 5/20/22.)

Yes, using version from `src` has the same issue.

**Comment by ThistleSifter** [comment]
Checking the PDK docs, it appears that `UseCheckboxes` is only part of `FCCtrlDataList` and not `FCCtrlListBox`.

**Comment by rpatters1** [comment]
That explains the discrepancy. On macOS `FCCtrlListBox` subclasses `FCCtrlDataList` but on Windows it subclasses `FCControl`. So that line of code should only be executed on Mac if at all.

I'm going to leave this for @cv-on-hub.

**Comment by cv-on-hub** [comment]
That errant code line is a mystery, introduced in version 0.56 around Feb 2022. No idea why it's there, but it suggests that the script has not been used previously by a Windows user! Should be fixed in PR #419
