### ISSUE TITLE
Possible enhancements for Cue Notes Create

### ISSUE THREAD

**Issue by asherber** [finale-lua/lua-scripts#421]
This is a great script, very easy to use. There are a few additional things I'd be interested in seeing in the plugin. I'm just getting my feet wet with RGPLua, but I'm happy to take a look at these myself later on.

1. It would be nice if the plugin could be a little smarter/offer some more options about placement of the cue name. Currently, the cue name is always placed above the staff. But if I have chosen to freeze cue stems down, I probably also want the cue name under the staff -- so that it's clearly labeling the cue, while the instrument's own whole rest floats above. It's not a big deal to manually drag the name down after creating the cue notes, but it would nice if the plugin incorporated functionality to autoposition the name when stems are down, and/or had an option in the dialog to choose where the name should go.

2. Along with the first point, it would be nice if the plugin offered a fourth option for stems besides up/down/normal: auto (or auto away). This would determine whether the majority of the cue notes lie above or below the middle line of the staff and would then freeze stems up (for above) or down (for below). And with the first point, the cue name would then be positioned appropriately.

3. It would be nice (a little) if there were a way to select multiple destination staves. For example, all the winds have been resting for 40 bars, and I want to use the same violin cue for all of them. Again, it's not a big deal to create the cue in one staff and then copy those measures to the desired staves, but it would be nice to have the option of doing it from the plugin.

cc: @cv-on-hub

**Comment by cv-on-hub** [comment]
These are all decent ideas, though not ones I want to work on, but free to do so yourself!

**Multiple Destination Staves** was high on my list, and was the cause of that errant "UseCheckboxes" code when I was trying to implement a selection list with checkboxes for easy multiple selections. But it seems that `FCCtrlListBox` doesn't (yet) offer that ability. (I haven't found a more suitable option under FinLua).

Otherwise there are so many conflicting factors affecting things like Cue Name positions, stem directions and so on, that I always prefer to create one ideally placed cue measure then duplicate it across the score.

**Comment by ThistleSifter** [comment]
`FCCtrlDataList` offers multiple selections, or at least it does on Windows. Is it the same on Mac?

**Comment by cv-on-hub** [comment]
Ah - you're perfectly correct @ThistleSifter. But that demands more mouse activity, and I was trying to add checkboxes to a simple menu item - `dialog:CreateListBox()`. Which doesn't offer checkboxes (and crashes on Win). Will ponder whether the mousing is worth the multiple-choice advantage.

**Comment by cv-on-hub** [comment]
@asherber: I think all of your concerns have been addressed by PR #426 and PR #431 and this Issue can now be closed.

**Comment by asherber** [comment]
Thanks, I appreciate your looking into these. The idea of "auto away" placement still interests me, but I'll look into that on my own time.
