### ISSUE TITLE
Files left in dist folder

### ISSUE THREAD

**Issue by asherber** [finale-lua/lua-scripts#424]
Commit 209c6a0 replaced `expression_set_to_parts_only.lua` and `expression_set_to_score_only.lua` with `expression_score_parts_assignment.lua` in the `src` folder. But when autopublish ran in commit 2890db6, it added the new lua file to `dist` and left the two old ones there as well.

I think the autopublish feature needs to learn how to remove files from `dist` if there is no corresponding file in `src`.

(I noticed this because it causes some problems with JWLuaMenu.)

**Comment by Nick-Mazuk** [comment]
I don't have time to debug this now, but this should be happening already…

Here's the line of code that should delete the old scripts. Essentially, on each commit it actually deletes every single script in the `/dist` folder, then recreates that folder. So I'm not entirely sure why you're seeing that behavior.

https://github.com/finale-lua/lua-scripts/blob/592a53e60432fd493ad9f2239e67e3c61418c3fc/.github/actions/bundle/src/index.ts#L22

**Comment by asherber** [comment]
Yeah, I saw that. I also thought it might have something to do with the action used to commit and push -- maybe it wasn't staging files properly. But I see that [it does](https://github.com/actions-js/push/blob/156f2b10c3aa000c44dbe75ea7018f32ae999772/start.sh#L49) `git add -A`, which should stage all changes, both adds and deletes.

**Comment by rpatters1** [comment]
I resolved this a while back. (The build process now deletes all files in the dist folder before processing.) So I'm closing this issue.
