### ISSUE TITLE
[HELP] Closing a modeless window

### ISSUE THREAD

**Issue by asherber** [finale-lua/lua-scripts#427]
How do you programmatically close a modeless window?

```lua
local dialog = finale.FCCustomLuaWindow()
local str = finale.FCString()
str.LuaString = "Foo"
local field = dialog:CreateStatic(0, 20)
field:SetText(str)
finenv.RegisterModelessDialog(dialog)
dialog:ShowModeless()
-- do some stuff
dialog:CloseWindow()
```

This gets me an error: `attempt to call method 'CloseWindow' (a nil value)`. Same thing happens with `TryToCloseWindow()`, `Hide()` and `DestroyWindow()`.

**Comment by rpatters1** [comment]
As I recall, a script cannot close a window. So it depends what you are trying to do. If you want the window to close when the user presses OK, you can set the window's `OkButtonCanClose` property. Otherwise, please provide more details.

**Comment by rpatters1** [comment]
P.S. In your code example above, all the code in your `-- do some stuff` comment would have to be inside callback functions attached to either a control or to the `OnCloseWindow` event.

**Comment by asherber** [comment]
I'm using the window as a progress indicator -- the script I'm working on takes several seconds to execute, and I wanted some way to show the user that there's something happening.

Yes, `ShowModeless()` returns right away, which is desired here -- I want to open a dialog, continue working in the main script, possibly update the dialog, then close the dialog.

**Comment by rpatters1** [comment]
Unfortunately, I don't think this is possible. Furthermore, on macOS the window probably would not even show progress due to how it refreshes the screen. (You would need to use a coroutine for it show progress on macOS. I ran into this very issue with the RGP Lua Class Browser.)

**Comment by asherber** [comment]
Bummer. I'm seeing some update issues on Win as well -- it seems that I can update fine with simple text, but if I update with the results of `string.format()` then only part of the string gets painted.

As it happens, while it would have been nice to have an updating progress message, in my case I guess it's enough to just display a dialog that says something like "Working...". When the function that includes the dialog code exits, the dialog falls out of scope and disappears.

**Comment by rpatters1** [comment]
I was going to suggest that if you allowed the dialog variable to fall out of scope, it might close the window. But that depends on Lua garbage collection, and I am not sure how reliably consistent that is, unless you are exiting the script anyway. 

Perhaps:

```Lua
dialog = nil
collectgarbage("collect")
```

However, RGP Lua is not expecting this behavior and it might crash Finale. You could evert *that* by setting finenv.RetainLuaState until all processing is complete.

**Comment by asherber** [comment]
Sorry, that was premature. When I change my code to just display a single static message instead of updating with progress, the dialog shows but the text never actually displays. It seems like a timing thing -- my other script code is continuing, and the Windows message loop never gets around to painting the control. The odd thing is that the text is set before I display the dialog -- I would think that the initial paint of the window would include the text.

**Comment by rpatters1** [comment]
If you use a coroutine it should work. Even though RGP Lua Class Browser no longer needs to show status (since it loads so quickly now), I think the coroutine is still there. They are pretty easy to add.

**Comment by rpatters1** [comment]
I'm looking at the code and think I could probably add it safely something like this:

```Lua
finenv.CloseRegisteredWindow(dialog)
```

The challenge has always been navigating out of Lua while being able to close the Lua state at the appropriate time.

**Comment by asherber** [comment]
I appreciate your looking at it. As it turns out, in my case the multi-second duration of my plugin's operation was due entirely to including the debuggee code, regardless of whether I had the debugger hooked up. Just for kicks, I commented out that `require`, and the plugin completed in sub-second time. 

Do you notice this with `mobdebug` and Zero Brane? Things run slower with the file included even if Zero Brane isn't listening?

**Comment by rpatters1** [comment]
I haven't noticed this, but what I have noticed is that—on Windows—there is a noticeable delay on the `require` statement while it waits for the socket request to timeout. This delay does not happen on macOS.

**Comment by asherber** [comment]
Yes, I noticed that delay (with other Lua debug extensions as well, I think, not just this one). I would have assumed that if the socket request times out the included file knows not to bother doing anything, but I guess it's still following along and prepping data, even if it doesn't get sent to the debugger.

No matter, it's easy enough to comment out the `require` block if I'm not actively debugging, and the fact that I don't need a progress window is a good result!
