### ISSUE TITLE
non-trivial enhancement for notehead.lua

### ISSUE THREAD

**Issue by cv-on-hub** [finale-lua/lua-scripts#438]
**notehead.lua inefficiency**
To change the notehead shapes on a measure of 20 twelve-note chords makes 240 calls to [notehead.lua ](https://github.com/finale-lua/lua-scripts/blob/master/src/library/notehead.lua)
Why not reduce that to 20 calls?

**Proposal**
Split out each function to implement a new `FCEntry` level function with minimal overhead.

**for example ...**
```
--[[
% entry_shape    -- replicate existing glyph-matching code
**[Internal]**
@ self (FCMTextExpressionDef)
@ entry (FCEntry)
@ shape_name (lua string) or (number)
]]
function notehead.entry_shape(entry, shape_name)
    local char, offset, resize = 0, 0, 100
    -- existing code ...
    return char, offset, resize
end

--[[
% change_one_note_shape -- from existing code
**[Internal]**
@ note (FCNote)
@ char (integer)
@ offset (integer)
@ resize (integer)
: (FCNoteheadMod) the new notehead mod record created
]]
function notehead.change_one_note_shape(note, char, offset, resize)
    local notehead_mod = finale.FCNoteheadMod()
    notehead_mod:EraseAt(note)
    -- (add in conditionals) ...
    notehead_mod.CustomChar = char
    notehead_mod.Resize = resize
    notehead_mod.HorizontalPos = offset
    notehead_mod:SaveAt(note)
    return notehead_mod
end

--[[
% change_shape -- the original code function
@ note (FCNote)
@ shape_name (lua string) or (number)
: (FCNoteheadMod) the new notehead mod record created
]]
function notehead.change_shape(note, shape_name)
    local char, offset, resize = notehead.entry_shape(note.Entry, shape_name)
    return notehead.change_one_note_shape(note, char, offset, resize)
end

--[[
% change_entry_shape -- the new code function
@ entry (FCEntry)
@ shape_name (lua string) or (number)
]]
function notehead.change_entry_shape(entry, shape_name)
    local char, offset, resize = notehead.entry_shape(entry, shape_name)
    for note in each(entry) do
        notehead.change_one_note_shape(note, char, offset, resize)
    end
end
```

I don't know if **Internal** library functions require special treatment like in `mixin` files.

**Comment by rpatters1** [comment]
Is there an actual performance problem this issue addresses? Or are you speculating that there is a problem? I have discovered over the years that performance problems are rarely where you expect them to be, and you can waste a lot of time trying to fix performance problems that turn actually not to be problems.

That said, any function that is acting on all the notes in an entry should be in `note_entry.lua`.  The clue is, if the first parameter is a `FCNoteEntry` it probably belongs in `note_entry.lua`. If it is a `FCNote` parameter it probably belongs in `notehead.lua`. (There may be some unfortunate exceptions to this rule, but I think it should be the goal.)

Finally, "internal" functions should be local, as follows:

```lua
-- you can document the parameters here if you wish, but don't set them up for inclusion by the doc generator
local change_one_note_shape = function(note, char, offset, resize)
    local notehead_mod = finale.FCNoteheadMod()
    notehead_mod:EraseAt(note)
    -- (add in conditionals) ...
    notehead_mod.CustomChar = char
    notehead_mod.Resize = resize
    notehead_mod.HorizontalPos = offset
    notehead_mod:SaveAt(note)
    return notehead_mod
end
```

However, this example does not look like an internal function to me. It looks like a proper external function that anyone might wish to call.

**Comment by ThistleSifter** [comment]
Just to add to what @rpatters1 said about not speculating, it's a good idea to get in the habit of testing  your theories. Here's a very simple benchmark script (adapted from http://lua-users.org/wiki/ObjectBenchmarkTests ) if you just want to evaluate execution time:

```lua
--[[
% run_benchmark

Runs a simple benchmark. For meaningful results, ensure that `iterations` is high enough.

@ name (string) Name of test, for output.
@ iterations (number) Number of iterations.
@ code (string) The code you want to execute, as a string.
]]
local function run_benchmark(name, iterations, code)
    local f = loadstring([[
        local iterations = ...
        local clock = os.clock
        local start = clock()
        for i = 1, iterations do ]] .. code .. [[ end
        return clock() - start
    ]])
    local t = f(iterations)
    print(name .. " (" .. iterations .. "x) - Total: " .. t .. "s\tAverage per iteration: " .. t/iterations .. "s")    
end
```

**Comment by Nick-Mazuk** [comment]
Just to add to that, benchmarking is really difficult to do. Your computer account username can affect the program's performance by up to 50%. It's more noticeable in a lower-level language like C++ or Rust, but the Lua JIT is fast enough that memory layout issues like this are still noticeable.

Here's a really interesting talk on benchmarking: https://youtu.be/r-TLSBdHe1A

FYI Carl, this post is not commenting on your proposal. But rather is an interesting tangent given this thread.

**Comment by cv-on-hub** [comment]
Thanks all for the thoughtful comments. Your collective wisdom exceeds mine by many orders of magnitude, and no - I'm not addressing an actual performance issue, and my concern is more aesthetic than practical. Spent so many years in the 90's trying to minimise code redundancy because storage and megaflops. (Probably kiloflops back then). 

A rough-and-ready benchmark (just using `os.clock`) gives 0.0635 seconds to change 1000 noteheads using the library routine on my Mac mini, so 0.0635 msec per notehead. Not a deeply significant overhead even with 50% inaccuracy. 

Will chalk this up to too much idling mind time and try to remember in future that `entry` events belong in `note_entry.lua`.

**Comment by rpatters1** [comment]
One reason this may be less costly than it looks is that Lua table lookups are very fast, even with string keys.

You could probably optimize the code in `change_shape` to calculate the note_type with fewer string comparisons and fewer table lookup. (I'm seeing up to three separate table lookups on `config` and no fewer than two.)

But since there isn't a performance problem we've identified, even that is probably not worth doing.

**Comment by cv-on-hub** [comment]
And here's that 50% inaccuracy:
changing 100,000 noteheads (an entire opera?) takes 3.2 seconds.
0.032 msec per notehead.

**Comment by jwink75** [comment]
https://youtu.be/H6_eqxh-Qok [https://youtu.be/H6_eqxh-Qok]

On 2/10/2023 7:30:43 PM, Carl Vine ***@***.***> wrote:
And here's that 50% inaccuracy:
changing 100,000 noteheads (an entire opera?) takes 3.2 seconds.
0.032 msec per notehead.

**Comment by cv-on-hub** [comment]
Which ones did you have in mind, your Majesty?
