### ISSUE TITLE
Add "Stems: away from center" to cue_notes_create

### ISSUE THREAD

**Issue by asherber** [finale-lua/lua-scripts#443]
@cv-on-hub I'm not sure the best workflow for this; I thought I'd open an issue instead of just opening a PR. Please see what you think about [these changes](https://github.com/finale-lua/lua-scripts/compare/master...asherber:lua-scripts:cue-notes-away-from-center). This adds an option to the plugin to freeze stems away from center -- that is, a cue line with most noteheads at or above the center line will get stems frozen up, otherwise it will get stems frozen down. 

*   Moved clef reset earlier, since we need to check staff positions in the correct clef
*   Calculate whether stems should be up or down and freeze appropriately
*   Freeze ties, tuplets, and slurs on the stem side of the cue

![](https://user-images.githubusercontent.com/5248041/218641349-7f7fd0ef-3039-4a16-8876-4997fdcc4ffd.png)

**Comment by asherber** [comment]
I'm also testing here a small script that will flip the direction of a cue created in the manner described above. I'm not sure if you're interested in looking at that as an additional menu item for this script.

My use case for all of this is that I always like to follow the "away from center" convention. Whether I use your script or the TGTools plugin, this has always meant that I have to look at the source material, mentally place it in the destination key/clef, figure out whether stems should be up or down, and set the plugin that way. If I guess wrong, I have to Undo and then go back and run the plugin again. I'd like to have the plugin figure this all out for me, on a per-staff basis, and if I happen not to like the result, I'd like to be able to easily flip the cue.

**Comment by cv-on-hub** [comment]
These types of modification depend entirely on user workflow. Previously I have NOT copied clefs from the cue source, since cues are hidden in the full score, and the final clef for the cue depends on the transposition and disposition of each part at that point in the music. (I normally employ SCORE IN C so transposition only happens in the part). This obviously affects cue stem direction. Sometimes the measure rests need to be above, sometimes below, and this is often not obvious until all transpositions and part clefs have been assigned. 

This means that the high level of finessing you propose serves no purpose for me at the preliminary stage. For the majority of staves in treble clef in C or Bb it is simplest to create a **single** cue, make all necessary corrections to the extracted cue then copy it to every other treble-clef staff. Quick and easy. Fine music layout is so convoluted, organic and personal that whatever minuscule enhancements you add in at the start will probably to need to be overridden later.

**Comment by asherber** [comment]
I'm not sure I understand your first comment about clef. Your script copies the cue music to the  destination staff, makes some adjustments, and then restores the original clef of the destination staff. All I did was restore the original clef earlier in the process, so that other tweaks could see the notes in their final staff positions. 

And yes, no plug-in will serve everyone's needs, and some things will need to be adjusted later. For example, I moved the whole rests after creating the cue in the example above. 

So are you saying that you're not interested in adding this functionality to your script? That's fine--I'll close this issue and just keep the changes in my local copy.

**Comment by cv-on-hub** [comment]
Sorry - I missed the link behind **these changes** and the fact that you'd already done the heavy lifting. Nicely achieved with a minimal change to the UI. I'm unsure about the handling of tie directions, and doubt that I'll find use for "away-from", but now you've done the work there's no reason not to include it. 

I'm not sure of the protocol here for changes to scripts created by others. Do you want to submit a PR?

PS: copying the cue clef to the destination is optional. The destination clef is only restored if "Copy" is disabled.  
`if not config.copy_clef then clef.restore_default_clef() ...`

**Comment by cv-on-hub** [comment]
Actually - my own script is up to v0.84. I'll submit the PR.

**Comment by asherber** [comment]
Yes, I've got the same logic surrounding clefs, just moved your block a little earlier in the function.

I'm glad you're amenable to adding this functionality. Are you interested also in "Flip Cue Notes" as an additional menu item? If so, I'd like to make a couple of other mods, for your approval -- refactoring this a little so that code is reusable.

**Comment by cv-on-hub** [comment]
`cue_notes_flip.lua` should be a separate script - user experience of a separate menu item will be the same. Nothing to stop it reading the same config file to identify the exact `cuenote_percent`.

**Comment by asherber** [comment]
It doesn't need to read any of the settings -- it just goes in and flips things. But it does use the same code that I added for freezing tuplets, ties, and slurs, which is why I thought that including it here would make sense. Again, if you don't want to, that's fine.

**Comment by asherber** [comment]
Okay, thanks -- I will submit a PR to your repo fork, and after you merge that you can send a PR to this repo. It will take me a little bit to tidy things up, probably later tonight (US Eastern time) or tomorrow.

**Comment by asherber** [comment]
Closed via #450
