### ISSUE TITLE
Ability to hook menu options.

### ISSUE THREAD

**Issue by rpatters1** [finale-lua/lua-scripts#454]
Does anyone see value in being able to hook menu options and attach scripts to them?

The idea came to me because I was trying to think of a way to get Finale to add cautionary accidentals without the user having to remember to run a plugin to do it. It occurred to me that it might be possible to intercept invocations of Music Spacing->Apply Note Spacing and have it run a cautionary accidentals script before running note spacing. The utility of this approach would depend entirely on whether hitting the `4` key invokes the menu item. (It probably isn't worth doing if it doesn't.)

For reference, my Patterson Plugins has a hook on the Save As and all the Undo menu options to perform various tasks. I know how to do it on both Mac and Windows, so in principle it ought to be possible for RGP Lua to attach a script to one.

**Comment by jwink75** [comment]
That actually sounds very useful to me, yes! And if you can solve the issue of Finale’s lack of automatic cautionaries once for all… That would be AMAZING!

-Jake

**Comment by rpatters1** [comment]
Sadly, hitting the `4` key does not invoke the menu, at least on Mac. But my Note Spacing plugin *does* register as a menu hit. Maybe there's another menu option that would be good, like the Save and/or Save As...

I'm open to ideas.

**Comment by ThistleSifter** [comment]
Do keyboard shortcuts (eg `Ctrl + S`) register as menu hits or would they bypass this?

**Comment by rpatters1** [comment]
The keyboard shortcuts that are "officially" assigned to the menu item (including, e.g., `ctrl-S` for Save) do indeed go through the menu hit process on both platforms. That's how was able to count on my intercepts for taking various action. (Basically, Patterson Plugins adds a file downgrade or upgrade warning at save time and it also monitors the menus for calls to Undo to tell any open modeless windows to update their selection region.)

**Comment by ThistleSifter** [comment]
Neat, I like the sound of that. You could do some neat tricks with it. Can hooks only be added for menu items or also for the underlying action they trigger (eg when a score is printed)?

Is it possible to have a hook for when a modeless `FCCustomLuaWindow` dialog becomes active/gains user focus (or whatever the correct term is)?

**Comment by rpatters1** [comment]
I can't think of a way to hook the underlying code. But is there a way to Print without using the menu?

For window activation, would it not be better just to have a callback function? In fact, there may already be one. (I need to check.) Tell me what you have in mind.

**Comment by rpatters1** [comment]
Version 0.66 add `FCCustomLuaWindow::RegisterHandleActivate` which allows Lua scripts to detect activation and deactivation of modeless dialogs. I have decided not to try to do menu hooks as the gain does not appear to be worth the pain.

Closing this issue.
