### ISSUE TITLE
Docs: Script installation out of date?

### ISSUE THREAD

**Issue by asherber** [finale-lua/lua-scripts#455]
https://www.finalelua.com/help/install/script has:

![image](https://user-images.githubusercontent.com/5248041/222750440-0ca8bc1b-2f37-4a0d-99e8-b2a6e916576d.png)

This description doesn't match for me on Windows with RGP Lua. Is this how things work on Mac? Or is this a description just for JW Lua?

**Comment by Nick-Mazuk** [comment]
I believe that's how JW Lua worked and we haven't updated it. Feel free to update the docs and send a PR.

Here's the relevant code:

https://github.com/finale-lua/jw-lua-scripts-docs/blob/6f01e66b6a3096ab6e8f2bba2280fd5ea3e27dc4/src/routes/help/install/script.svelte#L64-L73

**Comment by asherber** [comment]
Closed via https://github.com/finale-lua/jw-lua-scripts-docs/pull/25
