### ISSUE TITLE
[BUG] FCMCustomLuaWindow.lua lint error

### ISSUE THREAD

**Issue by rpatters1** [finale-lua/lua-scripts#468]
There is a lint error being reported on line `129` of FCCustomLuaWindow.lua. It appears to be a typo in that that the variable `f` is not defined or referenced anywhere else, so the error message will either fail on the concat or always say "not found in 'nil'".

@ThistleSifter

**Comment by ThistleSifter** [comment]
Thanks, fixing it now.
