### ISSUE TITLE
RequireSelection = true

### ISSUE THREAD

**Issue by asherber** [finale-lua/lua-scripts#477]
There are several scripts in the repo which require a selection but which do not specify `finaleplugin.RequireSelection = true`. This means that the scripts look like they're available in the menu when there is no selection, but then nothing happens when you click on them. In a couple of cases, the scripts call `region:SetCurrentSelection()`, which will crash Finale (at least on Win) if there is no current selection. It would provide a better user experience if all of these were updated.

I'm happy to take care of these and submit the PRs -- please just let me know if that's what you'd like.

*   [ ] @CJGarciaMusic   
    articulation\_delete\_duplicates
*   [ ] @rpatters1   
    articulation\_reset\_auto\_positioning  
    articulation\_reset\_positioning   
    expression\_reset\_positioning   
    note\_add\_augmentation\_dots
*   [ ] @jwink75   
    clef\_change   
    layers\_create\_whole\_rests\_1\_2   
    lyrics\_baseline\_reset   
    note\_bariolage   
    ties\_remove\_dangling
*   [x] @Nick-Mazuk   
    layers\_swap\_1\_2   
    playback\_mute\_notes\_in\_region   
    playback\_mute\_selected\_staves   
    playback\_solo\_selected\_staves   
    playback\_unmute\_all\_staves   
    playback\_unmute\_notes\_in\_region
*   [ ] @MichaelMcClennan   
    region\_replicate\_music

**Comment by Nick-Mazuk** [comment]
Feel free to create PRs for mine at least!

**Comment by rpatters1** [comment]
Is this resolved?

**Comment by asherber** [comment]
Only Nick has responded, and his scripts are fixed. The others are not. I can take care of them if you like.

**Comment by rpatters1** [comment]
Go for it.
