### ISSUE TITLE
[HELP] Changing Lyric's font    

### ISSUE THREAD

**Issue by zonga123** [finale-lua/lua-scripts#485]
**What do you need help with?**
I want to change the lyrics font in existing lyric's font!
When this script executed, but sometimes, finale was down in jw lua pug-in!!
I don't know why?
I guess, it's memory problem....T.T
Can you find my bug in this script?
Please, help me!  
Here is my script source.

**What have you tried?**

function plugindef()
   -- This function and the 'finaleplugin' namespace
   -- are both reserved for the plug-in definition.
   finaleplugin.MinFinaleVersion = "2016"
   finaleplugin.Author = "Jong-Ho, Park" 
   finaleplugin.Copyright = "Copyright 2023 J.H, Park  "
   finaleplugin.Version = "1.0.0"
   finaleplugin.Date = "March, 2023"
   return "Change Lylic's Font", "Change Lylic's Font", "After typing, You can change lyic's font!!"
end

local str, fstr = finale.FCString(), finale.FCString()
local dlgfont = finale.FCFontDialog(finenv.UI(), finale.FCFontInfo())
local Lyric_Block = finale.FCVerseLyricsText()
local type_Lyrics = {"Verse", "Chorus", "Section"}
local ctlOldPop, CurLyricNo, LyricCnt = 1, 0, 0

f, t, t1 = {}, {}, {}

function GetLyricsText(f, t, n)
    -- Get Data From Lylic Verse Text
    local tmpStr , tmpstr2, typStr = finale.FCString(), finale.FCString(), finale.FCString()
    local loaded_next = true
    if n ==0 then
        Lyric_Block = finale.FCVerseLyricsText()
    elseif n == 1 then
        Lyric_Block = finale.FCChorusLyricsText()
    elseif n == 2 then
        Lyric_Block = finale.FCSectionLyricsText()
    end
    if Lyric_Block:LoadFirst() then
        local NextID = Lyric_Block.ItemNo
        while loaded_next do
            Lyric_Block:GetText(tmpStr)
            local Finfo = tmpStr:CreateLastFontInfo()
            Finfo:GetNameString(tmpstr2)
            if Finfo.Bold then
                if Finfo.Italic then
                    typStr.LuaString = "Bold Italic"
                else
                    typStr.LuaString = "Bold"
                end
            else
                if Finfo.Italic then
                    typStr.LuaString = "Italic"
                else
                    typStr.LuaString = "Plain"
                end            
            end
            tmpStr:TrimEnigmaTags()
            if tmpStr.Length >= 2 then
                tmpstr2:AppendLuaString(" "..tostring(Finfo.Size).." ")
                tmpstr2:AppendString(typStr)  
                t[NextID] = tmpStr.LuaString
                f[NextID] = tmpstr2.LuaString
                LastCnt = NextID
            end
            NextID = NextID + 1
            while not Lyric_Block:Load(NextID) do
                NextID = NextID + 1
                if (NextID > 10000) then
                    loaded_next = false
                    break
                end
            end
        end
        return true, LastCnt
    else
        return false, LastCnt
    end
end

function ChangeFontEnigmaString(t, t1, fstr)
    for k, v in pairs(t) do  
        local tmpStr = finale.FCString()
        tmpStr.LuaString = v
        tmpStr:TrimEnigmaTags()
        tmpStr:InsertString(fstr,0)    
        t1[k] = tmpStr.LuaString
    end
end

str.LuaString = "Changing Font of lyric"
local dlgUsrInput = finale.FCCustomLuaWindow()
dlgUsrInput:SetTitle(str) 

str.LuaString = "Lyric:"
local static_lyric = dlgUsrInput:CreateStatic(0,3)
static_lyric:SetText(str)

local pop_LyricsType = dlgUsrInput:CreatePopup(40,0)
pop_LyricsType:SetWidth(65)
for k, v in pairs(type_Lyrics) do
    str.LuaString = v
    pop_LyricsType:AddString(str)
end

local edtCnt = dlgUsrInput:CreateEdit(110,0)
CurLyricNo = 1
str.LuaString = "1"
edtCnt:SetText(str)
edtCnt:SetWidth(30)

local ctl_updown = dlgUsrInput:CreateUpDown(140, 0)  

str.LuaString = "Lyric Count:"
local static_lyricCnt = dlgUsrInput:CreateStatic(162,3)
static_lyricCnt:SetText(str)

local edtMaxCnt = dlgUsrInput:CreateEdit(235,0)
str.LuaString = tostring(LyricCnt)
edtMaxCnt:SetText(str)
edtMaxCnt:SetWidth(30)

str.LuaString = "Font :"
local static_Font = dlgUsrInput:CreateStatic(0, 30)
static_Font:SetText(str)

str.LuaString = ""
local static_CurFont = dlgUsrInput:CreateStatic(40, 30)
static_CurFont:SetText(str)
static_CurFont:SetWidth(150)

local edtMain =  dlgUsrInput:CreateEdit(0,55)
edtMain:SetWidth(300)
edtMain:SetHeight(150)

str.LuaString = "Font"
local btnChangeFont = dlgUsrInput:CreateButton(235,25)
btnChangeFont:SetText(str)
btnChangeFont:SetWidth(60)

local btnOK = dlgUsrInput:CreateOkButton()
local btnCancel = dlgUsrInput:CreateCancelButton()

function SaveOneLyric(typLyric, LyricNo, t1)
     if typLyric ==0 then
        Lyric_Block = finale.FCVerseLyricsText()
    elseif typLyric == 1 then
        Lyric_Block = finale.FCChorusLyricsText()
    elseif typLyric == 2 then
        Lyric_Block = finale.FCSectionLyricsText()
    end 
    Lyric_Block:Load(LyricNo)
    Lyric_Block:DeleteData()
    local tstr = Lyric_Block:CreateString()
    tstr.LuaString = t1[LyricNo]
    Lyric_Block:SetText(tstr) 
    Lyric_Block:Save()
end

function PopTest()
    local CurPop = pop_LyricsType:GetSelectedItem()
    if ctlOldPop ~= CurPop then
        ctlOldPop =  CurPop
        local res, Cnt = GetLyricsText(f, t, CurPop)
        if res then
            local tmpStr = finale.FCString()
            tmpStr.LuaString = t[CurLyricNo]
            edtMain:SetText(tmpStr)
            tmpStr.LuaString = f[CurLyricNo]
            static_CurFont:SetText(tmpStr)
            tmpStr.LuaString = tostring(Cnt)
            edtMaxCnt:SetText(tmpStr)
            ctl_updown:ConnectIntegerEdit(edtCnt, 1, Cnt)
        end    
     else
     end
end

function cmd_handler(Ctrl)    
    local Ctrl_ID = Ctrl:GetControlID()
    if Ctrl_ID == pop_LyricsType:GetControlID() then
        PopTest()
    elseif Ctrl_ID ==  btnChangeFont:GetControlID() then
        if dlgfont:Execute() then
            local fontinfo = dlgfont.FontInfo
            fontinfo:MakeEnigmaString(fstr, NULL)
        end
        ChangeFontEnigmaString(t, t1, fstr)
    end    
end

function cmd_updnhandler(Ctrl)
    local Ctrl_ID = Ctrl:GetControlID()
    if Ctrl_ID == ctl_updown:GetControlID() then
        CurLyricNo = edtCnt:GetInteger()
            local tmpStr =finale.FCString()
            tmpStr.LuaString = t[CurLyricNo]
            edtMain:SetText( tmpStr)
            tmpStr.LuaString = f[CurLyricNo]
            static_CurFont:SetText(tmpStr)
    end    
end

dlgUsrInput:RegisterHandleCommand(cmd_handler)
dlgUsrInput:RegisterHandleUpDownPressed(cmd_updnhandler)

local ref = dlgUsrInput:ExecuteModal(nil)

if ref == 1 then
    SaveOneLyric(ctlOldPop, CurLyricNo, t1)
    else if ref == 2 then
    end
end

**Comment by rpatters1** [comment]
On Facebook, I suggested you debug the script with a Lua debugger. I am going to close this issue. If you have a more specific question, please make a new issue for it.
