### ISSUE TITLE
Has something changed in `mixin` with SetTypeMeasurementInteger? [BUG]

### ISSUE THREAD

**Issue by cv-on-hub** [finale-lua/lua-scripts#493]
Just noticed in the latest incarnation of `mixin` that dialog.CreateMeasurementEdit() edit boxes display a decimal point even if they are specified as 
`edit:SetTypeMeasurementInteger()`
and
`edit:SetMeasurementInteger(value)`

Unsure if this behaviour has been present before the latest amendments.
@ThistleSifter

**Comment by ThistleSifter** [comment]
For pretty much any measurement unit other than EVPUs, most values will display as a decimal. The `MeasurementInteger` part refers to the underlying EVPU value that is used for setting, getting and converting between units. 

I tried it with EVPUs as the display unit just now and got the following:
(Set) -> (Display)
144 -> 144
144.5 -> 145
144.4 -> 144

Was there a specific value/unit combination that you thought was giving incorrect results?

**Comment by cv-on-hub** [comment]
I'm getting the attached for all EVPU values. (The first unit is EFIX so demands decimal). This sustains through multiple changes of measurement unit, with EVPU's always turning up decimal. The source code is here: [gracenote_slash.lua](https://github.com/finale-lua/lua-scripts/blob/master/src/gracenote_slash.lua)

![EVPU_decimals](https://user-images.githubusercontent.com/105578039/230717590-a02ac4da-1100-4017-b620-edeaf7ba90e2.jpg)

**Comment by ThistleSifter** [comment]
What do you get if you try the following script?
```lua
local mixin = require("library.mixin")
local str = mixin.FCMString()
str:SetMeasurementInteger(44, finale.MEASUREMENTUNIT_EVPUS)
finenv.UI():AlertInfo(str.LuaString, "Test")
```

Also, what version of RGPLua are you running?

**Comment by cv-on-hub** [comment]
Ah - bingo! I was using Robert's 0.67b1 RGP bleeding edge. Reverted to 0.66 and it works as expected. So that's an interesting evolution in RGP. Sorry for casting aspersions on `mixin`!

**Comment by rpatters1** [comment]
This appears to be a difference in Lua 5.4 (which has true integers) and Lua 5.2. Is there a way around it?

**Comment by ThistleSifter** [comment]
The basic idea is straightforward (add calls to `math.tointeger` if in Lua >= 5.3), it's just a matter of finding a way of doing it that minimises the amount of spaghetti. There's also the possibility of adding `integer` and `float` to argument type validation.

@rpatters1 Could you send me a copy of the new version for testing?

**Comment by rpatters1** [comment]
You can use `math.floor` to do the same thing as `math.tointeger` without the need for Lua version checks.

The experimental version is on my download page:
https://robertgpatterson.com/-fininfo/-rgplua/rgplua.html

**Comment by rpatters1** [comment]
I should say, `math.floor` is *supposed* to convert it to an integer, but I haven't personally tested it. Another Lua-version-independent way would be to use `FCNumber`.
