### ISSUE TITLE
[BUG] Mixin crashing Transpose By Steps on every other invocation

### ISSUE THREAD

**Issue by rpatters1** [finale-lua/lua-scripts#498]
**Describe the bug**
Each time the Transpose By Steps dialog box opens, the next time it opens the plugin crashes.

**To Reproduce**
1. Go to 'Transpose By Steps'
2. Click on 'Cancel'
3. Go to 'Transpose By Steps' again
4. See error: bad argument 1 to SetLeft_ (number expected got nil)

**Expected behavior**
The dialog box should open.

I can proved more context if needed, but I am wondering if this is not related to the recent merge of mixin changes.

**Comment by ThistleSifter** [comment]
I've got a rough idea of what's gone wrong, I'll look into it.

**Comment by cv-on-hub** [comment]
My older version of the script didn't produce the error on 0.66 or 0.67b4, but a more recent version (with the new mixins) did.
