### ISSUE TITLE
[BUG] Lua Linter setup

### ISSUE THREAD

**Issue by rpatters1** [finale-lua/lua-scripts#5]
**Describe the bug**
This is not exactly a bug, but I don't see a better choice for where to put this.

The instructions for installing luac on Mac should be: `brew install lua`

Also, I have installed Visual Studio Code, lua (including luac), and lualinter. It says it is running in Visual Studio Code, with the default options. And my Code explorer shows the Lua Scripts folder that contains luaconfig.config. But I'm getting no de-linting joy. Any ideas?

**Comment by Nick-Mazuk** [comment]
Ok, I'll update the markdown file.

If you go to preferences (⌘ comma), is "Format on Save" turned on? If not, that's likely the issue. I'm also adding that to the markdown file.

**Comment by rpatters1** [comment]
All three of Format on Save, Paste, and Type were unchecked. But I'm still
not getting the love.

**Comment by rpatters1** [comment]
I mean, I'm still not getting the love after checking them.

**Comment by rpatters1** [comment]
I'm getting some formatting, but it seems to be generic. Like it
automatically maintains the indent levels for if end, for end, etc. But it
does not change the formatting if you put an if statement on a single line.

**Comment by Nick-Mazuk** [comment]
Interesting. Honestly, I don't know what's causing that. I had no trouble with the setup myself. I've tried to replicate the issue on my end, but I haven't been able to.

**Comment by Nick-Mazuk** [comment]
I may have written about the wrong plugin…

In short, I was wondering why my code formatting wasn't working anymore for Lua files and had to debug it. The `lua-linter` extension did not seem to be formatting the code. Instead, I had another extension called `vscode-lua-format` which formats the code.

This extension was already installed for me, but I had to add this to VS Code's `settings.json`

```json
"[lua]": {
    "editor.defaultFormatter": "Koihik.vscode-lua-format"
},
```

So my guess is that to get the code formatting, you need to:

1. Install [`vscode-lua-format`](https://marketplace.visualstudio.com/items?itemName=Koihik.vscode-lua-format)
2. Add the above snippet to your `settings.json`

If this works for you, I'll update the docs.

**Comment by rpatters1** [comment]
Remind me how to tell if it's working. Also, the settings.json I found was
in

~/Library/Application Support/Code

Adding it to that didn't seem to make any difference. Is there another
settings.json?

**Comment by Nick-Mazuk** [comment]
If everything is working, this…

```lua
if variable<2 then print('hello') end
```

…should be reformatted to this when you save:

```lua
if variable < 2 then
    print("hello")
end
```

If it is not formatted, you can try to manually trigger the format. The easiest way is to use the command palette (⌘⇧P) and type/select `Format Document`.

---

For the settings.json, I'm not 100% sure where it is on the disk. I always open it through the command palette (⌘⇧P) and select `Preferences: Open Settings (JSON)` to edit it straight in VS Code.

**Comment by rpatters1** [comment]
Can you show me the thing I need to add to settings.json in context? For
now, I've installed the vscode_lua_format thing, but I'm still not getting
any formatting.

Thanks,
Robert

**Comment by Nick-Mazuk** [comment]
Hate to beat a dead horse, but I was playing around with a new folder structure for Lua scripts this weekend and found out that this setting must be set for code formatting to work.

The formatter seems to not automatically pick up the config file.

<img width="455" alt="Screen Shot 2022-03-27 at 11 35 33 AM" src="https://user-images.githubusercontent.com/5659171/160295624-8722c999-f19e-4bf3-87ef-2f7074ab3629.png">

**Comment by Nick-Mazuk** [comment]
Just created PR https://github.com/finale-lua/lua-scripts/pull/156 which includes all my relevant settings and extensions for this repo.

(or at least I think it has all my relevant settings and extensions).

**Comment by rpatters1** [comment]
I applied the settings from the files in PR #156 and I now have Lua linter function in VS Code. It is complaining that it can't find the file `./luaconfig.config`. Is that something that should be added to the Pull Request?

**Comment by rpatters1** [comment]
A new issue I'm having is that it is adding in spurious line breaks when I save. Is there a setting to prevent this?

**Comment by rpatters1** [comment]
Never mind. I found `./luaconfig.config` (lol) and it also addressed the spurious line breaks.

**Comment by Nick-Mazuk** [comment]
Great! Glad you finally got it working and figured out those issues. Is it time to close this issue?
