### ISSUE TITLE
Possible [BUG] or incompatibility in RGP 0.67b3 and 0.67b4

### ISSUE THREAD

**Issue by cv-on-hub** [finale-lua/lua-scripts#503]
This older script doesn't use `mixin` and the error isn't detailed enough (for me) to pinpoint the cause. No error in 0.66 or 0.67b1.

[meter_set_numeric.lua](https://github.com/finale-lua/lua-scripts/blob/master/src/meter_set_numeric.lua)

`ERROR: Error decoding argument #2: The lua object can’t be cast to desired type`

**Comment by rpatters1** [comment]
Did it report a line number? This is almost certainly an omitted parameter. LuaBridge 3 is much pickier about parameters than LuaBridge 2.

**Comment by cv-on-hub** [comment]
No line number. Will trace through looking for missing params.

**Comment by cv-on-hub** [comment]
Found it. Line 70:
`str.LuaString = v`
'v' is an integer so this demands tostring(). So much for Lua's much-vaunted laxity on data types!

**Comment by cv-on-hub** [comment]
Code updated and problem solved. Interesting to see if many other datatype incompatibilities will emerge!

**Comment by rpatters1** [comment]
The lack of file:line number is solved in the latest LuaBridge3, so I am closing this issue.
