### ISSUE TITLE
Hashing of scripts

### ISSUE THREAD

**Issue by rpatters1** [finale-lua/lua-scripts#507]
This issue started as part of #495, and I want to break it out for its own discussion.

For RGP Lua to allow scripts in this repo to run as trusted, it needs some tracking information. My suggestion was as follows:

- When building the `dist` versions of the scripts, the yaml script injects a line at the end of the `plugindef()` function:

```lua
finaleplugin.HashURL = "https://raw.githubusercontent.com/finale-lua/lua-scripts/hash/<filename>.hash"
```

- The deploy script would run the Unix command `shasum -a 512 <filename>` as a final step on each file in the `dist` folder and store the results in a directory parallel to `dist` called `hash` with the `hash` extension.

RGP Lua then acts as follows:

- Downloads a whitelist of trusted url stems. Initially this list is probably only:

```
https://raw.githubusercontent.com/finale-lua/lua-scripts/hash
```

- If a script has a HashURL property that matches a whitelisted url-stem and its hash matches its contents and that hash is verified, it allows the script to run as trusted with no further checks. (This obviates the need to keep the script up to date.)
- If a script has a HashURL property that matches a whitelisted url-stem but no hash or the hash is unverified, it checks the script's contents against the hash at GitHub. If they match, it marks the hash as verified and allows the script to run as trusted. Otherwise it displays an error to the user.

If this scheme is workable, I could use some help with the top piece that injects the code into each `dist` script and creates the `hash` files. I'm very close to being ready to do this on the RGP Lua side.

**Comment by rpatters1** [comment]
This idea could be expanded to allow automatic updating of scripts. It would be contingent on the directory containing the scripts being writable with user-level privileges. But if it weren't that would also be an error message.

**Comment by ThistleSifter** [comment]
If I got the bundler directives idea up and running whichIi mentioned not too long ago so that the whole mixin directory didn't need to be bundled, would that make direct file comparison more feasible?

**Comment by rpatters1** [comment]
The thing is, I don't trust the scripts to know which items need to be bundled. It might be accurate but then it could end up being wrong after a modification.

I've been working on trying to get the `deploy.yml` to create the hashes. But for some reason GitHub refuses to run it after it failed the first time I pushed my branch. I can't figure out why.

**Comment by rpatters1** [comment]
Nevermind: I figured out how to get it to run.

**Comment by ThistleSifter** [comment]
Will there be a `finenv` property so that a script can detect if it's trusted or not? I'm working on an update to the mixin library and part of that is a whole lot more validation checks when loading mixins. It would be nice to be able to skip them for the `dist` versions of scripts.

**Comment by rpatters1** [comment]
Yes. finenv.TrustedMode (a boolean).

**Comment by rpatters1** [comment]
I have decided not to require Trusted mode for rewriting metatables of Finale classes. If a rewrite of mixins is ever forthcoming, we can revisit that decision then. In the meantime, I feel that of all the potential security risks, rewriting metatables is a very low one. Perhaps it is a bigger issue in some other environments, such as games. But Finale is a single-user environment where each script gets a fresh Lua state, so I just can't see where rewriting metatables is a big deal.
