### ISSUE TITLE
Hiccup with mixin.lua and RGP 0.67 Trusted Code

### ISSUE THREAD

**Issue by cv-on-hub** [finale-lua/lua-scripts#518]
RGP 0.67 is working well except for a hiccup with `mixin.lua` when `Enforce Trusted Code Policy` is enabled. This halts execution so masks any further incompatibilities. No problem without `Trusted Code`.

ERROR: mixin.lua:544: attempt to index a boolean value (local ‘meta’)
```
543 -- We need to retain a reference to the originals for later
544 local original_index = meta.__index 
545 local original_newindex = meta.__newindex
```
Using the `mixin` file set updated in #514 the same code is problematic here:    
ERROR: mixin.lua:719: attempt to index a boolean value (local ‘meta’)

**Comment by rpatters1** [comment]
You will have to either use the latest `dist` version or set the Trusted checkbox if you want to use `src`.

**Comment by cv-on-hub** [comment]
> set the Trusted checkbox if you want to use `src`

Got it!
