### ISSUE TITLE
Can `mixin` windows handle RadioButtonGroups?

### ISSUE THREAD

**Issue by cv-on-hub** [finale-lua/lua-scripts#520]
The code below works fine using `mixin.FCMCustomWindow()` (and various `finale.FCWindows`) but fails with `FCMCustomLuaWindow` and `FCXCustomLuaWindow`. In both latter cases clicking any radio button gives the message:
_ERROR: FCMCustomLuaWindow:134_
_Control with ID #10001 not found in ‘Handle Command’ (code=The lua function invocation raised an error)_
(RGP 0.67 with TrustedMode disabled - latest `mixin` files from `src`)

```
local mixin = require("library.mixin")
--local dlg = mixin.FCMCustomLuaWindow()
local dlg = mixin.FCMCustomWindow()
local b_group = dlg:CreateRadioButtonGroup(0, 0, 4)
local bttn = {}

for i = 1, 4 do
    bttn[i] = b_group:GetItemAt(i - 1)
    local str = finale.FCString()
    str.LuaString = "I am button " .. i
    bttn[i]:SetText(str)
end
b_group:SetSelectedItem(2)
dlg:CreateOkButton()
dlg:ExecuteModal(nil)

```
CC @ThistleSifter

**Comment by ThistleSifter** [comment]
No I haven't added that yet, I'm a bit behind on some of those. Do you need it for a script?

**Comment by cv-on-hub** [comment]
Not yet - just experimenting. So no hurry from my side.
