### ISSUE TITLE
Small slip in PDK 0.67 at FCCrossStaffMod

### ISSUE THREAD

**Issue by cv-on-hub** [finale-lua/lua-scripts#525]
`FCCrossStaffMod()` in PDK 0.67 includes the NULL method `SetNoteID()`. 
It's not present in the ClassBrowser.
The error is present back in PDK 0.54.

**Comment by cv-on-hub** [comment]
`FCCrossStaffMod:SetNoteID()` is not an implemented function. At least it crashes a script in any context that I can think of it being used. It is missing from the ClassBrowser and seems to be an erroneous inclusion on the PDK page.

**Comment by cv-on-hub** [comment]
> there is no need to call it

Which is why its inclusion would seem to be an error? (At least misleading and unnecessary)

**Comment by rpatters1** [comment]
There are many documented functions in the PDK Framework that are not hooked up in Lua. It is a C++ framework. I have scoured the source code to make sure that the "Lua supported" comments are complete and accurate, but I might have missed one. `SetNoteID` is not one of them.

**Comment by cv-on-hub** [comment]
Ah sorry - I've not paid enough attention to the "Lua-supported" caveat.
