### ISSUE TITLE
FinaleLua website not updating

### ISSUE THREAD

**Issue by rpatters1** [finale-lua/lua-scripts#576]
I just merged a PR that removed a couple of script files and replaced them with another that does the same thing. The deploy action scripts seems to have run without errors (except the first time, which was weird). But the finalelua.com website has not updated. It is still dishing up the outdated scripts.

Does anyone have any idea what's going on?

@asherber @Nick-Mazuk

**Comment by asherber** [comment]
What should I be seeing?

**Comment by rpatters1** [comment]
You should not see separate scripts for
 
- Mute selected staves
- Solo selected staves

instead there should be

- Playback selected staves (which is a group that includes both the Mute and Solo options.)

**Comment by asherber** [comment]
Looks like a problem with the deployment engine.

![image](https://github.com/finale-lua/lua-scripts/assets/5248041/67cfd00b-84dd-402a-ac24-c73aa58977b0)

**Comment by rpatters1** [comment]
And I don't have access to Vercel to see what the error is. It looks like it started on Aug. 17, so I am going back to see if there is a PR on that date that could have caused it.

**Comment by asherber** [comment]
Maybe Nick's subscription expired?

**Comment by rpatters1** [comment]
Possibly, but it corresponds to a lua-scripts PR on Aug. 17 that may be throwing of the deployment script in Vercel. I'm rewriting it to see if it makes a difference.

**Comment by Nick-Mazuk** [comment]
## Root cause

NodeJS v14 is discontinued. All new Vercel deployments need to use NodeJS v18+.

## Next steps

I've updated the settings in Vercel to build using NodeJS v18. However, the site uses at least one dependency not compatible with this NodeJS version.

Over the weekend I can update dependencies to get site building again. However if any of you want to try, feel free. Pushing new code should start a new build.

**Comment by rpatters1** [comment]
Thank you Nick! It might be helpful if I could access the Vercel page. I set up a Vercel account linked to my GitHub, but when I click on the "Details" link for the error, it sends me to 404. That make me think I don't have access to the Vercel page for Lua Scripts.

**Comment by rpatters1** [comment]
I feel certain that this was triggered when I merged all the dependabot PRs on Aug. 17. Would rolling those back get us back up as a temporary measure?

**Comment by asherber** [comment]
@rpatters1 I think the issue is in the jw-lua-scripts-docs repo, not in this one, so your Dependabot merges in this repo aren't relevant. I've got a little time this morning and need to clear my head, so I'm going to see if I can update dependencies per Nick's suggestion.

**Comment by asherber** [comment]
Well, that didn't last long!

I've got Node 14 locally. I thought I'd start from a known good state and then try upgrading to Node 18. I cloned the repo and ran `pnpm i` to install dependencies, then `pnpm dev:open` to view the development site, and I got an error:

```
SyntaxError: Unexpected token ':'
    at wrapSafe (internal/modules/cjs/loader.js:1029:16)
    at Module._compile (internal/modules/cjs/loader.js:1078:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:979:32)
    at Function.Module._load (internal/modules/cjs/loader.js:819:12)
    at Module.require (internal/modules/cjs/loader.js:1003:19)
    at require (internal/modules/cjs/helpers.js:107:18)
    at nodeRequire (C:\Users\Aaron\Documents\Projects\jw-lua-scripts-docs\node_modules\.pnpm\vite@2.4.4\node_modules\vite\dist\node\chunks\dep-c1a9de64.js:73479:17)
    at ssrImport (C:\Users\Aaron\Documents\Projects\jw-lua-scripts-docs\node_modules\.pnpm\vite@2.4.4\node_modules\vite\dist\node\chunks\dep-c1a9de64.js:73431:20)
    at eval (/src/lib/components/docsearch.svelte:7:31)
```

I also tried `pnpm build`, just for kicks, and I got: 

```
> Using @sveltejs/adapter-vercel
> Unknown file extension ".css" for C:\Users\Aaron\Documents\Projects\jw-lua-scripts-docs\node_modules\.pnpm\@docsearch+css@3.1.1\node_modules\@docsearch\css\dist\style.css
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".css" for C:\Users\Aaron\Documents\Projects\jw-lua-scripts-docs\node_modules\.pnpm\@docsearch+css@3.1.1\node_modules\@docsearch\css\dist\style.css
    at new NodeError (internal/errors.js:322:7)
    at Loader.defaultGetFormat [as _getFormat] (internal/modules/esm/get_format.js:71:15)
    at Loader.getFormat (internal/modules/esm/loader.js:105:42)
    at Loader.getModuleJob (internal/modules/esm/loader.js:243:31)
    at async ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:78:21)
    at async Promise.all (index 3)
    at async link (internal/modules/esm/module_job.js:83:9)
 ELIFECYCLE  Command failed with exit code 1.
```

So I guess this will need Nick's help to resolve.

**Comment by rpatters1** [comment]
I got the production build to run. It's emitting an error from the code in @sveltejs and I have no idea how to fix it. The suggested fix seems wrong. It appears that the code is expecting a package called `createFilter` in `vite`, but it isn't finding it. I am at a dead end here.

**Comment by rpatters1** [comment]
Okay, so I was able to get the jw-lua-scripts-docs to build as follows:

- update to latest version of node
- update npm and pnpm

run:

```
pnpm i
npm update
```
I may have repeated that.

The `pnpm test` command seems to have disappeared. It isn't in package.json, and I don't know where else it might be.

When I run the server, the website is completely garbled, so I am reluctant to submit this as a PR. It seems like it could break the website even further. We really need some input from @Nick-Mazuk.

**Comment by rpatters1** [comment]
@asherber resolved this. Site is building again.
