### ISSUE TITLE
Future of the Repo

### ISSUE THREAD

**Issue by cv-on-hub** [finale-lua/lua-scripts#583]
Just wondering if we need to consider the future health of the repo, especially in light of the situation with issue #576.

The documentation suggests that the repo was largely set up by Nick in collaboration with CJ, but as they have other priorities now it feels like everything relies, unfairly, on the continuing stellar contribution of @rpatters1. 

I'm not ringing alarm bells but suggesting combined consideration ... even something as mundane as the continuing registration cost of [finallua.com](https://www.finalelua.com).

**Comment by asherber** [comment]
Just a note that this repo and the website are technically separate entities. The repo seems to be just fine, but the website (which has its own repo) is currently not publishing updates. I think @Nick-Mazuk needs to look into this.

**Comment by rpatters1** [comment]
The problem seems to be at Vercel rather than GitHub, but even though I created a Vercel account, I can't seem to access the info I need to. It always returns 404-not found.

**Comment by asherber** [comment]
Right, that's because this build project is set up under Nick's account. Only Nick has access to it.

**Comment by asherber** [comment]
As Nick [pointed out](https://github.com/finale-lua/lua-scripts/issues/576#issuecomment-1692691804), this can be fixed without access to Vercel by updating the website repo to be compatible with Node v18. I [tried](https://github.com/finale-lua/lua-scripts/issues/576#issuecomment-1703860156) but was getting too many errors.

**Comment by cv-on-hub** [comment]
> this repo and the website are technically separate entities.

I'd never registered that because I only came here after `finalelua` told me to. Nonetheless, both entities are much more powerful working in tandem than in isolation.

**Comment by cv-on-hub** [comment]
The silence in this ghost town is deafening and must be some cause for concern. It would be a great pity for all the terrific work put into the website and its GitHub link to simply dry up and float away with the next tumbleweed.

@Nick-Mazuk - is it too much work to contemplate handing the keys to `finalelua` over to someone else?

**Comment by jwink75** [comment]
I confess I haven’t followed ALL the developments, but am right that there is currently an active problem with the way the scripts get  packaged and delivered? Most of those discussions go well over my level of technical knowledge!Sent from my iPhoneOn Oct 19, 2023, at 1:48 PM, Carl Vine ***@***.***> wrote:﻿
The silence in this ghost town is deafening and must be some cause for concern. It would be a great pity for all the terrific work put into the website and its GitHub link to simply dry up and float away with the next tumbleweed.
@Nick-Mazuk - is it too much work to contemplate handing the keys to finalelua over to someone else?

**Comment by asherber** [comment]
The bits that actually build and deploy the website after new scripts have been committed live in a Vercel account that belongs to @Nick-Mazuk. They haven't been working for a couple of months because they use a deprecated Node version. I took a look at doing the necessary upgrades, but even the current state of that project doesn't compile correctly for me, and I don't know enough about Node to troubleshoot.

I think that Nick's help is needed to get the Vercel project working again.

**Comment by rpatters1** [comment]
I have been buried in what's turning into a massive enhancement of RGP Lua that will introduce significant new features that are taking a lot of time to complete all the details. I'm hoping @Nick-Mazuk will come along and address the deployment issues. If I start getting close to a release and he hasn't done it, I'll see if I can jog him. (This is always hit-or-miss.)

**Comment by rpatters1** [comment]
@asherber resolved our issue for now.
