### ISSUE TITLE
[BUG] Hash doesn't match

### ISSUE THREAD

**Issue by asherber** [finale-lua/lua-scripts#589]
**Describe the bug**
The stored hash for `cue_notes_create.lua` is incorrect. The stored hash starts with `cc1c2284ef49e53`, but the computed hash starts with `A5FBB1E1C476854CA`. I get an error message every time I try to use this script.

I have the `dist` folder configured as an auto folder. I currently have `Trusted` checked on this folder, and I also have the general setting `Enforce Trusted Code Policy` unchecked. This script still won't run. (Other scripts seem to be fine.)

This shouldn't be related to #576, because I think it's GitHub Actions in this repo that are supposed to update and publish the hash.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Finale Version 27
 - JW Lua Version v0.67
 - Script Name: "Create Cue Notes"

**Comment by rpatters1** [comment]
Have you updated to the most current master branch? I checked in a change yesterday or the day before that would have changed the hashes.

Otherwise, I can only guess it has something to do with line endings. The hash is working correctly for me.

**Comment by asherber** [comment]
Yes, I have the latest master branch.

When I hash other scripts in dist, what I get matches the stored hash. But for this file it does not.

**Comment by rpatters1** [comment]
That makes me think there is a crlf somewhere in your copy of it.

**Comment by asherber** [comment]
Nope, no carriage returns.

**Comment by asherber** [comment]
When you hash the file from master locally, do you get `cc1c` or `a5fb`?

**Comment by asherber** [comment]
Okay, it's a git-related user issue. Closing.
