### ISSUE TITLE
What's worse: a non-updated FinaleLua site or an updated garbled site?

### ISSUE THREAD

**Issue by rpatters1** [finale-lua/lua-scripts#600]
As a followup to #576 and #583, I would like to pose a question to interested parties on this repo.

I have been able to update the dependencies on the `jw-lua-scripts-docs` repo so that it builds and runs the preview. The problem is that the preview is completely garbled, due (I imagine) to an issue with the css. I do not know enough about this to judge if the problem is more likely an artifact of the preview or if it would be an real issue on the production Vercel site.

If I merge the updated dependencies and then force an update from this repo, I see one of three possible outcomes:

1. The build process still fails and the Vercel site remains un-updated.
2. The build process succeeds and the Vercel site updates with garbled CSS (not ideal).
3. The build process succeeds and the Vercel site works as expected (this is the outcome we want).

Unfortunately, I think the least likely outcome is 3. The problem is, I am virtually certain that whatever happens, there is no going back, because the current main branch does not build. So what's worse? A stale functioning site or an updated garbled site (that still functions but is user hostile)? Obviously, the goal is that either would be a temporary status for the site.

It would be helpful if someone (maybe @asherber if not @Nick-Mazuk) would duplicate my results. Maybe more than one pairs of eyeballs could figure out this CSS issue.

My steps to be able to build the site were:

- update Node on your dev box to the latest version. (This was the crucial step for me.)
- update npm and pnpm on your dev box.
- clone the `jw-lua-scripts-docs` repo and run the follow steps from a terminal in order:

```
pnpm i
npm update
pnpm i
pnpm build
```

**Comment by asherber** [comment]
I'll try this later today -- although as I posted in the other thread, when I tried to do this previously, it didn't work for me. Nick implied that some dependencies needed to be updated to work with latest Node.

**Comment by asherber** [comment]
Which version of Node are you using? Nick [said](https://github.com/finale-lua/lua-scripts/issues/576#issuecomment-1692691804) that he updated Vercel to use v18 -- which is *not* the current version.

**Comment by rpatters1** [comment]
v21.1.0. I don't recall what my earlier version was, maybe 16. Is there a way to fall back to 18?

**Comment by asherber** [comment]
Uninstall and reinstall? Or `nvm` on Mac?

**Comment by rpatters1** [comment]
It fought me and I lost. I'm not going to try to do it, since it mostly seems to work except for the css.

**Comment by rpatters1** [comment]
I managed to try with node 18, and it failed to build. (Ominously, the error messages had to do with css.) But now my environment is completely hosed, and I am struggling to recover it. I truly hate this cluster-f**k.

**Comment by jwink75** [comment]
Has anyone tried to reach Nick through other methods, like maybe Facebook messaging?

On 11/8/2023 7:40:47 AM, rpatters1 ***@***.***> wrote:
I managed to try with node 18, and it failed to build. (Ominously, the error messages had to do with css.) But now my environment is completely hosed, and I am struggling to recover it. I truly hate this cluster-f**k.

**Comment by rpatters1** [comment]
>Has anyone tried to reach Nick through other methods

Yes

**Comment by cv-on-hub** [comment]
Sorry that I'm no help on the tech side. To return to the original question, "stale" is better than "garbled".

**Comment by ThistleSifter** [comment]
I agree that for now non-updated is better.

I'll join all the king's horses and all the king's men and have a go at put humpty together in the next few days. My computer has been almost unusable for a while but it appears to be functioning again.

**Comment by Nick-Mazuk** [comment]
Yeah sorry, I've been extremely busy lately. I tried updating the site's dependencies and could not get it to build either.

It may just be easiest to redo the site.

Just in case I don't have too much time to contribute, I just invited @asherber and @rpatters1 to the Vercel account.

Ultimately, the main technical challenge of the site is to convert Markdown into HTML/CSS/JS. So if I started over, I might choose to use https://gohugo.io/ instead which is designed for this purpose. Hugo's also much more stable long-term (the JavaScript ecosystem is a gigantic mess where everything's reinvented and deprecated every 2-4 years).

Sorry that you all have had to pester me so much.

**Comment by asherber** [comment]
I disagree with your opinion about Node. (And I'm not even a Node dev!) It's a perfectly fine platform, as long as you take the time to periodically keep things updated. Node 12 came out 4.5 years ago and has been out of support for a while; given the fact that the current LTS is v20, I think it's reasonable for GitHub to say that they're deprecating it.

It looks like GH has actually been using Node 16 [since this summer](https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/), and our actions (in this repo) have been running without error. Still, I'll take a look and see if anything needs to be explicitly updated, at least to get rid of the warning.

**Comment by rpatters1** [comment]
@asherber resolved this. Site is building again.

**Comment by jwink75** [comment]
Hallelujah! That’s great news!

Well done, Aaron!

**Comment by cv-on-hub** [comment]
Brilliant. Many thanks Aaron.

**Comment by rpatters1** [comment]
@asherber resolved this. (Thanks again!)
