### ISSUE TITLE
create cue notes suggested changes

### ISSUE THREAD

**Issue by gtmalone** [finale-lua/lua-scripts#620]
On the cue notes create script, include the option to omit chord symbols.  Most of the time I only want the notes especially on a drum staff.   

Also, for cues on a drum staff, make the notes single pitch and show the notes and rests on the first space above the top line on the staff.  This will save the steps for single pitch and move rests. 

Thanks for listening!

**Comment by cv-on-hub** [comment]
This is my script so I should comment. Thanks for the note about chord symbols - I'll add those to the "optional copy" items. (Never use them myself so forgot about them!) Also ... I have a new amendment now awaiting packaging called "Cue Notes Overlay" designed for cues to sit above existing (played) music - which never copies chord symbols.

The percussion staff issue is highly personalised, and making the assumption that everybody would want all of their drum notes reduced to single pitch is a really big leap. Unless I can envisage a more universal solution it will remain something you have to do manually. Maybe create a new script that automates that percussion reduction BEFORE it becomes a cue?

**Comment by rpatters1** [comment]
Is this issue resolved? If it was resolved by one of the PRs I just merged, the best way to be sure it gets closed is to reference by number (e.g. #620) it in the description of the PR.

**Comment by cv-on-hub** [comment]
Yes - sorry. #622 addressed several other matters and I forgot that it was sparked here. @gtmalone didn't have any other comments so that should resolve the issue.
