### ISSUE TITLE
Example scripts: new repo or new folder in this repo?

### ISSUE THREAD

**Issue by rpatters1** [finale-lua/lua-scripts#626]
I have some test scripts that exercise features of the PDK Framework. I am thinking they might be useful as learning aids and so I would like to post them somewhere public. I could then link back to them from the PDK Framework documentation.

Do people think it makes more sense to add them to this repo in a subfolder? Or would they be better off in their own repo? The first two I have in mind are

- a test script I developed to test features of `FCCtrlTextEditor`
- a test script I developed to test features of `FCCtrlDataList` (including forthcoming features in v0.70.)

I could imagine adding more over time.

**Comment by jwink75** [comment]
I feel like a subfolder here is totally appropriate

**Comment by cv-on-hub** [comment]
> I feel like a subfolder here is totally appropriate

Agreed. And a great value add.

**Comment by rpatters1** [comment]
Whoops. Forgot to resolve it. This is resolved with #627.
