### ISSUE TITLE
[BUG] Mixin crashes JW Lua

### ISSUE THREAD

**Issue by rpatters1** [finale-lua/lua-scripts#631]
**Describe the bug**
Creating a `FCMCustomWindow` with JW Lua crashes Finale.

**To Reproduce**
Run this code:
```lua
local mixin = require("library.mixin")
local dlg = mixin.FCMCustomWindow()
```

Finale crashes on the 2nd line.

**Desktop (please complete the following information):**
 - OS: macOS 12.7.1
 - I tried both Finale 27.4 and 25.5
 - JW Lua Version 0.54
 - Script Name: mixin.lua

**Additional context**
I tried creating an FCMString (i.e., `mixin.FCMString()`) and it did not crash Finale and appeared to work. This appears to be a problem specific to `FCMCustomWindow` and its subclasses.

I am not certain how much effort is worth expending to support JW Lua, but we have made an effort for the `mixin` library to support it up till now.

@ThistleSifter

**Comment by ThistleSifter** [comment]
Do you have any error information? I don't have a functioning computer at the moment, so while I source some parts the best I can do is educated guesswork.

**Comment by rpatters1** [comment]
I haven't tracked it down past what I documented. It crashes Finale (at least on macOS), and even when running my debugger there is no symbol info, so I don't get anything useful where it crashes. My JW Lua on windows will no longer open the UI (due to SciLexer.dll issue), so I haven't been able to try it on Windows.
