### ISSUE TITLE
[BUG] Mixin FCMCustomLuaWindow does not support `FCCtrlComboBox`

### ISSUE THREAD

**Issue by rpatters1** [finale-lua/lua-scripts#638]
I was able to add "ComboBox" in the `create_control` loop in `FCMCustomLuaWindow.lua`, which allows the dialog to open. But re-displaying it causes the script to crash. It needs a `FCMCtrlCombobox.lua`.

In the context of the PDK Framework, `FCCtrlComboBox` is a combined popup menu and edit text box. It in fact is a subclass of `FCCtrlEdit`. So we can think of it conceptually as an edit text box with a popup button attached. `FCMCtrlComboBox.lua` is going to need everything in `FCMCtrlEdit.lua` and `FCMCtrlPopup.lua` combined. My questions are:

- Is there a way directly to reuse those?
- Does the fact that the PDK Framework `FCCtrlComboBox` actually inherits from `FCCtrlEdit` have any bearing on this?

For reference, on Windows both `FCCtrlPopup` and `FCCtrlComboBox` are combo boxes. (The former is read-only.) On macOS, they are unrelated controls that bear a superficial resemblance to each other. (`NSPopUpButton` vs. `NSComboBox`.)

@ThistleSifter

**Comment by ThistleSifter** [comment]
> But re-displaying it causes the script to crash. It needs a `FCMCtrlCombobox.lua`.

That's weird, in theory it should at least function without one (putting aside extra bells and whistles).


> * Is there a way directly to reuse those?

If it isn't inherited, then it needs to be copied and pasted for now. So you'd inherit all of the `FCMCtrlEdit` methods, but you'd need to copy the ones you want from `FCMCtrlPopup`.

**Comment by rpatters1** [comment]
Never mind. This is a bug in RGP Lua.
