### ISSUE TITLE
[BUG] RTFNotes eats AdditionalMenuOptions et al

### ISSUE THREAD

**Issue by rpatters1** [finale-lua/lua-scripts#686]
**Describe the bug**
When the bundler builds the `RTFNotes` from `Notes` it erroneously eats the `AdditionalMenuOptions`, `AdditionalUndoText`, and `AdditionalDescriptions` if they follow `Notes`, which they often do. 

**To Reproduce**
Examine any `dist` version of a script with `AdditionalMenuOptions`. `beam_selected_region.lua` is an example.

@asherber

**Comment by asherber** [comment]
Hmm, that didn't come up in my testing, but I'll look into it today.

**Comment by rpatters1** [comment]
Actually, it looks like it may be eating everything to the end of `plugindef` (from `Notes`).

**Comment by asherber** [comment]
Can't think of why but thanks for the info.

**Comment by asherber** [comment]
Just to confirm: When you say "eats", you mean that the items which appear after `Notes` are getting presented in the RTF -- but they're also still present in `plugindef()`, right? That's what it looks like to me, just want to make sure you're not seeing something else.

**Comment by rpatters1** [comment]
That's right, and the double [[]] in the subsequent fields also messes up the "stringness" of `RTFNotes`.

**Comment by asherber** [comment]
Yup, I see it, fixing it now.

**Comment by asherber** [comment]
Hmm, the PR didn't kick off a deployment. I need to grab some lunch, will investigate in a bit.

**Comment by asherber** [comment]
Oh, it did, I was reading Vercel wrong. Everything look okay to you?

**Comment by rpatters1** [comment]
Looks good to to me.
