### ISSUE TITLE
Improve RTFNotes line spacing

### ISSUE THREAD

**Issue by asherber** [finale-lua/lua-scripts#703]
After seeing some Notes dialogs with more text, I think the default line spacing is too tight. 

[Here](https://gist.github.com/asherber/db488b4b299acf58bd4f6baf17ed5f00) is a script that shows the same paragraph of text with 5 different gradations of line spacing. Here is what it looks like on Windows:

![image](https://github.com/finale-lua/lua-scripts/assets/5248041/e25e68e9-e2eb-44b1-ade3-d9242e22e271)

I'd be grateful if:

- Someone could post a screenshot of what this looks like on Mac
- Others could weigh in on which spacing they like best -- keeping in mind that it would be nice to agree on one option that works on both OSes.

**Comment by rpatters1** [comment]
It looks similar on Mac.

<img width="652" alt="Screen Shot 2024-02-18 at 8 45 57 AM" src="https://github.com/finale-lua/lua-scripts/assets/11542367/d1110fdd-6f46-483c-b3f1-5a29e3847827">

**Comment by asherber** [comment]
@rpatters1, @cv-on-hub, @jwink75, @ThistleSifter Any opinion about which spacing to use? I'm leaning towards 2, could also see 3.

**Comment by rpatters1** [comment]
I have no strong opinion. Weakly, I prefer wider line spacing to narrower, but I'll go with the flow on this.

**Comment by cv-on-hub** [comment]
I go for 3 on Mac, though 2 would be acceptable - a tiny adjustment from the current "1" spacing.

**Comment by ThistleSifter** [comment]
Number 1 is too tight, but otherwise I don't have a strong preference.

**Comment by asherber** [comment]
Well...I created a branch in my fork to implement this change, and I successfully pushed to my fork...but somehow it looks like it also pushed to this repo. Never seen that before.

In any case, this has been resolved and published. The consensus seemed to favor # 3 over # 2, so that's what I went with (110% line spacing).

**Comment by cv-on-hub** [comment]
I like the 110% spacing on Mac. Thanks!
