### ISSUE TITLE
Zombie Repository lua-scripts-2

### ISSUE THREAD

**Issue by cv-on-hub** [finale-lua/lua-scripts#714]
When trying to make a clean local fork of __lua-scripts__ my desktop GitHub seems to have created a top-level clone within GitHub called __[lua-scripts-2](https://github.com/finale-lua/lua-scripts-2)__. I can't work out how to delete it so anyone with suitable authority should go ahead and get rid of it.

**Comment by asherber** [comment]
It's just in your local, @cv-on-hub -- not in the repo on GitHub.

**Comment by cv-on-hub** [comment]
> I've deleted it.

Great. Thank you!
