### ISSUE TITLE
[BUG] System Up/Down Nudgers always use top system margin

### ISSUE THREAD

**Issue by rpatters1** [finale-lua/lua-scripts#87]
I would like to modify the system up/down nudgers to use Distance Between instead of Top Margin. In general, a non-zero system margin offers much less flexibility with page layout than leaving the vertical system margins at zero.

If others feel that Top Margin is preferable, we could implement it so as to use the margin when it is non-zero or the distance between when it is zero or when the result would be negative.

What do y'all think? (It's a simple change.)

**Comment by Nick-Mazuk** [comment]
A year late, but I'm fine with this change.
